minecraft-server/start-minecraft.sh

using exec to properly shutdown the Minecraft process

propagate SIGTERM to the Minecraft process

---

minecraft-server/minecraftforge_spider.py

As per issue #14, here is the Minecraft Forge scraper.
Problem: We would like to get recommended and latests downloads for the Minecraft Forge installer
Solution: Use Scrapy (python module) to obtain the links and write them to a json file
- python
- scrapy
```{.sh}
pip install scrapy
scrapy runspider minecraftforge_spider.py -o latest.json
```
```{.json}
[{
"latest": {
"forge_recommended": ["10.13.2.1291"], 
"forge_latest": ["11.14.1.1333"]
}, 
"versions": [{
"url": ["http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.5.2-7.8.1.738/forge-1.5.2-7.8.1.738-installer.jar"], "minecraft": ["1.5.2"], "type": "forge_latest", "id": ["7.8.1.738"], "time": ["06/17/2013 10:36:00 AM"]}, {
"url": ["http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.5.2-7.8.1.737/forge-1.5.2- …
```

Add initial version of forge download scraper

---

minecraft-server/Dockerfile
minecraft-server/README.md
minecraft-server/start-minecraft.sh

Resolves #14 

---

minecraft-server/README.md

[mc] Update README to describe attach mode

---

minecraft-server/start-minecraft.sh

Added the ability to select forge version by adding -e FORGEVERSION=10.13.3.1403-1.7.10 or -e FORGEVERSION=RECOMMENDED

Added the ability to select forge version

---

minecraft-server/README.md
minecraft-server/start-minecraft.sh

Interested in easy whitelisting for your Minecraft image?

Whitelist players

---

minecraft-server/Dockerfile
minecraft-server/README.md
minecraft-server/start-minecraft.sh
minecraft-server/start.sh

[minecraft] Pass GID as docker option

---

minecraft-server/README.md
minecraft-server/start-minecraft.sh

The popular mod site https://www.feed-the-beast.com provides server
modpacks to go with their client modpacks. These server modpacks
include a custom start script that must be used to launch the server.

Add Feed-The-Beast (FTB) server modpack support

---

elasticsearch/start

Needed for Cattle support (see #140)

Subnet ignoring

---

minecraft-server/start-minecraft.sh

This was added such that Sponge servers are supported.
(For Sponge: TYPE=FORGE, MODPACK=[zip including sponge plugins and jar], MODCONFIG=[sponge configuration])

Add support for a zip file of mod configs to be supplied!

---

minecraft-server/start-deployFTB

making use of all the server properties magic in ftb packages ..

---

minecraft-server/start-deployFTB
minecraft-server/start-finalSetup04ServerProperties

as the last fix did not stick, i removed it and fixed it properly along with a few other inconsistencies.
This fix works properly.

Fix properly set ftb properties

---

minecraft-server/start-minecraftFinalSetup

as this is just a redundant remnant, i removing this line is save and works better

this somehow deleted the correctly modified properties file.

---

minecraft-server/README.md
minecraft-server/start-finalSetup04ServerProperties

Hello there,
I started to use the minecraft server docker file but one of the server properties I use is missing. With this modifications it can be configured via environment variable.
Please review it!

[mc] Add snooper enabled toggle

---

minecraft-server/start-finalSetup01World

My world just got overwritten when i re-created the container. this should hopefully solve it..

only download world if there is no preexisting world

---

minecraft-server/README.md
minecraft-server/start-minecraftFinalSetup

[Feature] add JVM_DD_OPTS

---

minecraft-server/README.md

Removes `CONSOLE: "false"` environment variable causing issue #319

Update docker-compose example in README

---

minecraft-server/start-deployFTB

This PR updates the curseforge urls to their new format

update curseforge urls

---

start-minecraftFinalSetup

fix settings.cfg and preserve semicolons if present

---

README.md
start-finalSetup04ServerProperties

Allow to set spawn-protection setting with an env variable.

Add spawn protection setting

---

README.md
start-finalSetup05EnvVariables

Some plugins use this extension.
Also, reformatted the code and made documentation more explicit.

Support .conf extension for config files

---

README.md

@itzg what do you think?
I don't know why Atom removed a space on the end of the line using GitHub Markdown.

Running Minecraft on a different Java version

---

Dockerfile
log4j2.xml
start-minecraftFinalSetup

Add customized log file with 7 day retention

---

README.md

fixed the link to curseforge mod list

---

start-configuration
start-deployFabric
start-deployForge
start-minecraftFinalSetup

This is a tentative fix for #492, by adding a /data prefix. I probably missed some (`bash` is not my strong suit)

add some /data prefixes in missing places

---

README.md

I searched on issue list to find how to do it (#263 and #463). Both ways worked.

Add explanation for timezone config on README

---

README.md
start-finalSetup05EnvVariables

Hello,
This PR add possibility to use secrets in environment variables.
**NOTE**: This could be adapted to server properties
Thanks.

Add possibility to use secrets in environment variables

---

README.md

I removed the -e VERSION entries except for the ones in the section that describes that functionality.
fixes #537

removed version entries except for the version section. fixes #537

---

start-deployFTB

Added more names to possible modpack startup scripts. Fixes #595

More filenames for modpack start scripts

---

start-deployCF

Replace LegacyJavaFixer path with new working url.
More info:
https://github.com/LexManos/LegacyJavaFixer/issues/4#issuecomment-625978049

Update deprecated LegacyJavaFixer path.

---

Dockerfile

Closes #678
I'm not entirely sure if I PRed it to right branch. I couldn't find option to pull it to new branch 😢

Add Java 15 support

---

files/autopause/autopause-daemon.sh
files/autopause/autopause-fcns.sh

The fix on master (#711) didn't merge correctly into the ubuntu-based image.

Fix autopause multiarch interface selection

---

README.md
start-minecraftFinalSetup

Initially thank you for this awesome work that you've created. It brings joy to me and my family.
I am hosting my server on AWS and I have realized that I cannot change the icon that I've initially set. I have made a change to allow the server icon to be overridden.

Add an option to override the icon which already has been set.

---

README.md

This can only be found by digging through issues (#156), so it would make sense to mention it in the README.

Document LEVEL_TYPE: BIOMESOP

---

start-configuration

Update Invalid Server Type Logging Message

---

start-finalSetupWorld

Remove existing world data when FORCE_WORLD_COPY

---

README.md
start-deployAirplane
start-minecraftFinalSetup

[Flare](https://blog.airplane.gg/flare/) is a new profiler created by the Airplane team, which is present in Airplane as well as its downstreams. This PR adds an option to add its required Java flags.

Add option for Flare flags

---

README.md
start-configuration
start-deployCanyon

[Canyon](https://github.com/canyonmodded/canyon) is a fork of CraftBukkit for Minecraft Beta 1.7.3, created by some of the Velocity team members such as @astei. It includes multiple enhancements whilst also retaining compatibility with old Bukkit plugins and mods as much as possible.
This commit adds initial support for this project, allowing for downloading of the latest successful build, similar to the Airplane support method. Future PRs (or revisions to this PR) will add support for specific build or version retrieval.

Add support for Canyon server for b1.7.3

---

README.md
start-deployMohist

This PR updates the repo/job URLs for Mohist, which seem to have changed.

Update the Mohist URLs

---

start-deployForge

Fix Forge download

---

README.md

The Purpur team recently elected to drop Airplane patches. This PR reflects that change.

Reflect Pupur's removal of Airplane patches

---

README.md
start-deployAirplane

Of course branch names are case sensitive.. stupid me.

Correct AirplanePurpur branch name

---

README.md

Today i opened an issue #938 and i don't want people to make the same mistake i did and potentially ruining their worlds, so i included a tiny line that says "case sensitive" near the explanation of the variable.

Improve readme with extra info

---

start-finalSetupMounts

Fix unquoted COPY_MODS_DEST and COPY_CONFIG_DEST variables

---

start-deployPurpur

This PR moves the Purpur deploy script to their new V2 downloads API.

Update to new Purpur download API

---

start-deployAirplane

Not sure if I missed this or if it's yet another change to the CI, but here we are again.

Reflect different jar names for airplane/airplanepurpur

---

README.md

Added a little description to the README about the information found around #999.
_May not be in your wording, also maybe not in the best english, so feel free to reject or edit this pr_

docs: generator_settings json for 1.13+

---

examples/docker-compose-rlcraft.yml

Adding an RLCraft compose example for future reference.

Add RLCraft example

---

README.md

docs: clarify java8-multiarch tag for TYPE=SPONGEVANILLA in README

---

scripts/start-deployPurpur

Purpur domain now redirect to purpurmc.org

Update Purpur version API

---

scripts/start-finalExec

CVE:
https://www.randori.com/blog/cve-2021-44228/
More context:
https://mobile.twitter.com/slicedlime/status/1469150993527017483
Closes #1177 
Signed-off-by: Pascal Sthamer <sthamer.pascal@gmail.com>

security: patch log4j remote code execution vulnerability

---

.github/workflows/build-multiarch.yml
scripts/start-finalExec

fix: use Mojang log4j config file fixes by version

---

Dockerfile
scripts/start-deployFabric

fix: qualify Fabric server jar by installer version

---

examples/docker-compose-paper.yml

for submission to update docker-compose-paper.yml example in https://github.com/itzg/docker-minecraft-server/tree/master/examples

Created new template for docker-compose-paper.yml

---

bin/mc-send-to-console
scripts/start

Write to console pipe as minecraft user

---

scripts/start-deployCF

This was broken for me when upgrading Valhelsia 3.4.4 to 3.4.8 on tag java8. I'm using the same strategy as the other serverJar variable to fix this

Fix script not deleting old version files when upgrading

---

scripts/start-finalExec

fix(forge): improved tracking and use of Forge run.sh

---

.github/workflows/discord.yml

ci: Reference branch and html URL from completed workflow in discord workflow

---

scripts/start-setupModpack

fix: speedup generic pack update check

---

Dockerfile
scripts/start-utils

https://github.com/itzg/mc-image-helper/pull/13

fix: bumped mc-image-helper to 1.16.3 to use specific user agent

---

scripts/start-configuration

Fix PATH for annoying docker providers

---

.github/workflows/build-multiarch.yml

Pin java8-multiarch to 8u312 due to Forge

---

README.md
scripts/start-deployPufferfish
tests/setuponlytests/pufferfish/docker-compose.yml
tests/setuponlytests/pufferfish/require.sh
tests/setuponlytests/pufferfish/verify.sh

Fixing pufferfish bug, as well as adding a test for it.

added variables for pufferfish, also added setup only test

---

tests/setuponlytests/pufferfish/docker-compose.yml
tests/setuponlytests/pufferfish/require.sh
tests/setuponlytests/pufferfish/verify.sh
tests/setuponlytests/test.sh

ci: adjusted pufferfish test

---

Dockerfile

Picks up https://github.com/itzg/mc-image-helper/pull/23

Provide better debug logs with mc-image-helper get

---

.github/workflows/pr.yml
tests/setuponlytests/pufferfish/docker-compose.yml
tests/setuponlytests/pufferfish/require.sh

Re-fixed pufferfish tests

---

Dockerfile
examples/docker-compose-spiget.yml
scripts/start-spiget
tests/setuponlytests/spiget/docker-compose.yml
tests/setuponlytests/spiget/verify.sh

Verify content type when downloading SPIGET_RESOURCES entry

---

bin/mc-send-to-console

mc-send-to-console skips user change when non-root

---

scripts/start-finalExec
scripts/start-spiget
scripts/start-utils
tests/setuponlytests/spiget/docker-compose.yml
tests/setuponlytests/spiget/verify.sh

Determine SPIGET file type from API

---

scripts/start-spiget
scripts/start-utils

Silence content type error for external spiget resources

---

scripts/start-spiget
tests/setuponlytests/spiget/docker-compose.yml
tests/setuponlytests/spiget/verify.sh

Use file content to detect spiget resource type

---

README.md

Add hint that SPONGEVANILLA requires VERSION to README (#1452)

---

scripts/start

Corrected default of UID/GID via start script

---

scripts/start-deployForge

Fix forge using 1.17+ version after downgrade

---

Dockerfile

Updated rcon-cli to support variables cleanup

---

files/log4j2.xml

Help prevent disk flooding, as discussed https://discord.com/channels/660567679458869252/660567682751528981/965426963927928893

Updated rolling logs config to also be size based

---

scripts/start-deployForge

Fix invalid -s arg with TYPE=FORGE

---

README.md

docs: Cleanup RCON_CMDS examples

---

examples/docker-compose-rlcraft.yml
scripts/start-deployForge
scripts/start-finalExec
scripts/start-setupModpack
tests/fulltests/vanilla-latest/docker-compose.yml

Constrain GENERIC_PACK base detection depth

---

README.md

https://github.com/itzg/docker-minecraft-server/issues/1492#issuecomment-1133907334

docs: Corrected image tag in FTB example

---

scripts/start-deployPurpur

Fixed older versions of purpur that were not removed
Signed-off-by: Bensuperpc <bensuperpc@gmail.com>

Fixed older versions of purpur that were not removed

---

build/ubuntu/install-packages.sh
scripts/start-deployCF

CurseForge modpacks use run.sh when present

---

Dockerfile

Pull in https://github.com/itzg/mc-server-runner/pull/30

Provide clearer log when minecraft server process fails

---

.gitattributes
Dockerfile
scripts/start-deployCF

Place EULA file into subdir managed by ServerSetup

---

scripts/start-setupModpack

due to my very limited knowledge of bash there may still be issues with my approach.
#1562

tried my best to fix `itzg/docker-minecraft-server/issues/1562`

---

scripts/start-setupModpack
tests/setuponlytests/packwiz/docker-compose.yml
tests/setuponlytests/packwiz/verify.sh
tests/setuponlytests/packwiz/web/index.toml
tests/setuponlytests/packwiz/web/mods/architectury-api.pw.toml
tests/setuponlytests/packwiz/web/pack.toml
tests/setuponlytests/test.sh

Handle packwiz bootstrap installer already being present

---

scripts/start-deployCF

TYPE=CURSEFORGE also looks for start.sh

---

docker-compose.yml

Resolves compatibility with [gamenetics.io](gamenetics.io)

Added top-level docker compose file

---

scripts/start-deployFTBA

Output expected files when FTBA prep fails

---

scripts/start-deployCF

Updated LegacyJavaFixer Download URL

---

Dockerfile
scripts/start-deployForge

Switched to mc-image-helper
Uses https://github.com/itzg/mc-image-helper/pull/51

Perform clean Forge version changes

---

scripts/start-setupServerProperties

Don't show server properties by default and obscure passwords

---

README.md

docs: Corrected versions required for FTBA

---

examples/docker-compose-generic-pack-tnp5.yml

Added the config example I used in #1602

Added example for GENERIC_PACK TNP5

---

Dockerfile

Correctly parse modrinth dependencies declared as embedded

---

Dockerfile

Fixes #1697 
Includes 
- https://github.com/itzg/mc-image-helper/pull/56
- https://github.com/itzg/mc-image-helper/pull/57

Upgrade mc-image-helper to 1.22.4

---

scripts/start-setupModpack

Corrected Modrinth usage with TYPE=FORGE

---

Dockerfile

Pick up https://github.com/itzg/mc-image-helper/pull/62

Allow image helper get to use user info

---

Dockerfile

Pull in https://github.com/itzg/mc-monitor/pull/22

Upgrade mc-monitor to allow option to use mcutils for long FML2 listings

---

scripts/start-setupModpack

Prevent generic modpack overwriting eula file

---

README.md

Emphasize java 8 requirement for Forge < 1.18

---

Dockerfile

https://github.com/itzg/mc-server-runner/releases/tag/1.8.2

Bump mc-server-runner to 1.8.2

---

scripts/start-deployCF

Use HTTP accept when downloading CF modpack

---

build/alpine/install-packages.sh
build/ubuntu/install-packages.sh

Changes related to issue: #1842

Added nfs client support packages.

---

scripts/start-deployFTBA

Discovered while investigating https://github.com/itzg/docker-minecraft-server/discussions/1820 and https://discord.com/channels/660567679458869252/660569641550217327/1047654597151432814

Let FTB installer manage file removal during version change

---

scripts/start-deployForge

Restore FORGE_INSTALLER (again) using mc-image-helper

---

Dockerfile
README.md
scripts/start-deployAutoCF

Brings in https://github.com/itzg/mc-image-helper/pull/96

For AUTO_CURSEFORGE, provide the option to force include mods

---

Dockerfile

Fix usage when given forge installer is in data directory

---

Dockerfile

Picks up https://github.com/itzg/rcon-cli/pull/29

Upgrade rcon-cli to 1.6.1

---

Dockerfile

Pull in https://github.com/itzg/mc-image-helper/pull/125

Upgrade image helper to debug log file download duration and rate

---

Dockerfile
README.md

Sorry for the slow PR
closes #1871

Modrinth per project version type declaration

---

Dockerfile

Resolves #1946 
Pulls in https://github.com/itzg/mc-image-helper/pull/135

auto-cf: correctly handle modpack slug that clashes with mod slug

---

files/auto/autopause-daemon.sh
files/auto/autopause-fcns.sh

autopause: improve network interface lookup

---

Dockerfile

Pull in https://github.com/itzg/mc-image-helper/pull/136

auto-cf: properly handle mod URLs with unicode

---

Dockerfile
files/auto/autopause-daemon.sh
files/auto/autopause-fcns.sh

For #1943 
Pulls in https://github.com/itzg/mc-image-helper/pull/137

Use mc-image-helper for checking autopause interface

---

Dockerfile

Reported [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1071909516133793863)

Handle interpolating sync'ed files when value has dollar sign

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/142

auto_cf: allow networking timeouts to be configured

---

files/auto/autopause-fcns.sh

Discussed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1075239043295608932)

With autopause check for process in stopped or sleep state

---

files/auto/autopause-fcns.sh

Reverts itzg/docker-minecraft-server#1963

Revert autopause check for process in stopped state

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/143
Resolves #1965

autocf: longer default request timeout

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/147
Resolves #1972

autocf: ensure modpack listing API always provides up to date

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/148
Resolves #1975

autocf: modpack fileName included in manifest

---

Dockerfile
scripts/start-setupModpack

Brings in https://github.com/itzg/mc-image-helper/pull/151
Resolves #1973

modrinth: adapt version lookup to API changes

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/156

Unzip Modrinth files that are zips

---

scripts/start-configuration

Verify java compatibility for AUTO_CURSEFORGE

---

Dockerfile
scripts/start-deployForge

Pulls in https://github.com/itzg/mc-image-helper/pull/161

Allow for latest Forge version to be behind vanilla version

---

Dockerfile

Helps #2011 
Pulls in https://github.com/itzg/docker-minecraft-server/pull/2006

Extract versions from provided Forge installer

---

scripts/start-setupModpack

Fixing Modrinth projects support for non-Forge

---

Dockerfile

Resolves issue discussed in https://github.com/itzg/docker-minecraft-server/pull/2022
Pulls in https://github.com/itzg/mc-image-helper/pull/172

autocf: fixed issue where exclude file alone was ignored

---

build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Fix curl usage for knockd install

---

Dockerfile

Resolves #2031 
Pulls in 
- https://github.com/itzg/mc-image-helper/pull/176
- https://github.com/itzg/mc-image-helper/pull/177

forge: support version discovery of 1.5, 1.7 installer

---

Dockerfile

Resolves #2037 
Pulls in https://github.com/itzg/mc-image-helper/pull/180

autocf: ensure modpack query is not cached too much

---

Dockerfile

For #2045 
Pulls in https://github.com/itzg/mc-image-helper/pull/182

autocf: determine mod file availability from downloadUrl

---

Dockerfile

Resolves #2044 
Pulls in https://github.com/itzg/mc-image-helper/pull/185

Downloads handle content disposition filename with RFC 2047 encoding

---

Dockerfile

Helps with #2007 
Pulls in https://github.com/itzg/mc-image-helper/pull/186

Redacts sensitive headers from debugs like with AUTO_CURSEFORGE

---

Dockerfile
scripts/start-deployAutoCF

Reported [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1094243891399630849)
Pulls in
- https://github.com/itzg/mc-image-helper/pull/193
- https://github.com/itzg/mc-image-helper/pull/194

autocf: use VERSION resolved from modpack

---

Dockerfile

Resolves #2091 
Pulls in https://github.com/itzg/mc-image-helper/pull/204

modrinth: ensure non-required dependency doesn't mask explicit project request

---

Dockerfile

Pull in https://github.com/itzg/mc-image-helper/pull/210
cc @Hayden-J-C

Add JSON5 support for patch files

---

Dockerfile
README.md
scripts/start-deployAutoCF

Resolves #1639 
Pulls in
- https://github.com/itzg/mc-image-helper/pull/195 
- https://github.com/itzg/mc-image-helper/pull/212

autocf: allow manifest JSON to be provided

---

build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Add webp package for dynmap support

---

Dockerfile
README.md

Pulls in https://github.com/itzg/mc-image-helper/pull/227

Support Quilt mod loader for Modrinth modpacks

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/231

auto-cf: handle download repo files with + for spaces

---

.github/workflows/build-multiarch.yml

Fixes regression introduced by #2051
For #2183

Build: corrected primary image taggging

---

Dockerfile
docs/mods-and-plugins/index.md
examples/geyser/docker-compose.yml
scripts/start-deployPaper
scripts/start-setupModpack
scripts/start-utils

Also
- modernized PaperMC downloading
Pulls in https://github.com/itzg/mc-image-helper/pull/239

Improved handling of MODS and PLUGINS lists using mcopy

---

docs/configuration/server-properties.md

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1117883383456993332)

Add ENFORCE_SECURE_PROFILE to docs table

---

docs/configuration/server-properties.md

And removed some redundant ones.

Sort "other server property mappings"

---

docs/misc/contributing/building.md

docs: fixed building page formatting and added base image info

---

Dockerfile
scripts/start-deployPurpur

Resolves #2213 
Pulls in https://github.com/itzg/mc-image-helper/pull/244

Use mc-image-helper for Purpur

---

docs/misc/contributing/building.md

docs: corrected base image use in docs

---

Dockerfile
examples/quilt/docker-compose.yml

Resolves #2232 
Pulls in https://github.com/itzg/mc-image-helper/pull/249

Fix up-to-date handling of MODS/PLUGINS/MODS_FILE

---

scripts/start-deployCF

Reconcile VERSION for TYPE=CURSEFORGE

---

Dockerfile
files/cf-exclude-include.json

Also
- removed carry-on from default exclusions
Pulls in https://github.com/itzg/mc-image-helper/pull/251
Resolves #2239

auto_cf: allow explicit inclusions to override default exclusions

---

Dockerfile

Resolves #2140 ...hopefully
Pulls in https://github.com/itzg/mc-image-helper/pull/255

modrinth: reduce API pressure with initial bulk get of projects

---

Dockerfile

Update rcon-cli to remove config file loading message

---

Dockerfile
docs/types-and-platforms/mod-platforms/auto-curseforge.md
examples/.gitignore
examples/rlcraft/docker-compose.yml

Pulls in https://github.com/itzg/mc-image-helper/pull/258
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1122679576422797312)

auto_cf: write mods needing manual download to file

---

scripts/start-finalExec

Remove .mc-health.env when not needed

---

Dockerfile

Docker scout report:
```
Your image  itzg/minecraft-server                 │    0C     1H     8M    35L
```

misc: upgrade all Go tools to Go 1.20

---

scripts/start-deployFTBA

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1126521732883288156)

Corrected VERSION resolution with FTBA mod platform/type

---

scripts/start-setupEnvVariables

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1128319278429524088)
Follow up to #2278

Allow blank REPLACE_ENV_VARIABLE_PREFIX when processing in-place files

---

Dockerfile

Brings in https://github.com/itzg/mc-image-helper/pull/263

auto-cf: stop startup with info when manual mod downloads are needed

---

docs/versions/java.md

https://discord.com/channels/660567679458869252/660569641550217327/1132039251366789262

docs: corrected Java 20 typo

---

Dockerfile

Resolves #2307 
Pulls in https://github.com/itzg/mc-image-helper/pull/273

auto-cf: updated API parsing for NeoForge mod loader type

---

Dockerfile

For #2311 
Pulls in https://github.com/itzg/mc-monitor/pull/54

Set mc-monitor timeout less than health check timeout

---

Dockerfile

Resolves https://github.com/itzg/mc-image-helper/issues/283
Pulls in https://github.com/itzg/mc-image-helper/pull/284

packwiz: cache maven metadata

---

examples/docker-compose-ngrok.yml

Added Example Compose for using ngrok with server to bypass networks that block port forwarding.

Add Ngrok example

---

Dockerfile
docs/configuration/server-properties.md
notes/rbac-processing.mmd
scripts/start-setupRbac

- Resolves #2330 
which also
- Resolves https://github.com/itzg/docker-minecraft-server/issues/2309
- Resolves https://github.com/itzg/docker-minecraft-server/issues/1862
- Resolves https://github.com/itzg/docker-minecraft-server/issues/2290
- Resolves #925 
Pulls in https://github.com/itzg/mc-image-helper/pull/288

Improve whitelist/ops handling with caching, UUID, and offline support

---

Dockerfile

Resolves #2345 
Pulls in https://github.com/itzg/mc-image-helper/pull/289

Fixed copying of OPS_FILE and WHITELIST_FILE

---

Dockerfile

Resolves #2344 
Pulls in https://github.com/itzg/mc-image-helper/pull/291

modrinth: ensure requested loader for modpack is optional

---

docs/types-and-platforms/server-types/forge.md

[Observed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1141991944990490694)

docs: clarified FORGE_VERSION usage

---

scripts/start-deployBukkitSpigot

Corrected use of VERSION when building Bukkit from source

---

Dockerfile
docs/configuration/server-properties.md
scripts/start-setupRbac

Resolves #2357 
Pulls in https://github.com/itzg/mc-image-helper/pull/301

Support skipping existing whitelist/ops files and restore as default

---

Dockerfile
docs/misc/healthcheck.md
docs/versions/minecraft.md
scripts/start-finalExec

disable healthcheck for unsupported versions fixes #2359

---

docs/types-and-platforms/server-types/bukkit-spigot.md

docs: note the apparent death of getbukkit

---

Dockerfile

Resolves #2299 
Resolves https://github.com/itzg/mc-image-helper/issues/313

Properly resolve latest file URLs from bukkit

---

Dockerfile
docs/types-and-platforms/server-types/forge.md
scripts/start-configuration
scripts/start-deployNeoForge

Resolves #2362 
Pulls in https://github.com/itzg/mc-image-helper/pull/317

Added support for NeoForge

---

Dockerfile

Resolves #2417 
pulls in https://github.com/itzg/mc-monitor/pull/67

autopause: allow for DEBUG to be enabled

---

scripts/start-setupModpack

Resolve Modrinth projects for Quilt specifically

---

Dockerfile

Resolves #2428 
Pulls in https://github.com/itzg/mc-image-helper/pull/326

Sanitize mod file subpath in Modrinth modpacks

---

scripts/start-setupRbac

misc: Corrected utils import for start-setupRbac

---

Dockerfile

Resolves #2433 
Pulls in https://github.com/itzg/mc-image-helper/pull/328

Ensure server.properties is processed as UTF-8

---

docs/configuration/server-properties.md

https://github.com/itzg/docker-minecraft-server/issues/2433#issuecomment-1764826319

docs: clarify multi-line MOTD

---

Dockerfile
docs/misc/contributing/development.md
docs/types-and-platforms/mod-platforms/auto-curseforge.md
scripts/start-deployAutoCF

Resolves #2294 
Pulls in https://github.com/itzg/mc-image-helper/pull/332

auto-cf: support excluding files from overrides

---

docs/configuration/server-properties.md

- Update generator_settings documentation in server-properties.md

<doc>(server-properties):

---

scripts/start-setupServerProperties

From [Discussion in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1169383707166122084)

Fail startup if server properties processing fails

---

Dockerfile

Resolves https://github.com/itzg/mc-image-helper/issues/336
Pulls in https://github.com/itzg/mc-image-helper/pull/337

Gracefully handle corrupt/invalid auto-install manifest files

---

Dockerfile
docs/configuration/server-properties.md
scripts/start-setupServerProperties

Resolves #2478 
Also resolves #2477

Provide option to escape unicode in server.properties

---

Dockerfile
scripts/start-setupRbac

- Resolves #2482 
- Resolves #2481

All pre-escaping unicode in server.properties

---

Dockerfile
docs/configuration/server-properties.md

For https://github.com/itzg/docker-minecraft-server/issues/2474

Process placeholders in server properties values

---

docs/configuration/server-properties.md
scripts/start-configuration
scripts/start-setupServerProperties

Retain declared version for placeholder usage

---

docs/configuration/jvm-options.md

[Discussed in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1173442259262382110)

docs: document JMX_PORT

---

docs/configuration/server-properties.md

docs: clarify the resolved value for %VAR%

---

Dockerfile

Stream file downloads to avoid 2GB limit

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/356

modrinth: report error when no matching modpack version is available

---

scripts/start-deployModrinth

Fixed unbound variable error for MODRINTH_EXCLUDE_FILES

---

Dockerfile

Resolves #2541 
Pulls in https://github.com/itzg/mc-image-helper/pull/364

Use Forge shim jar as entrypoint for >= 1.20.4

---

.github/workflows/discord.yml

Updated release action does better at parsing/displaying release notes.

Update release action

---

Dockerfile

neoforge: handle malformed version entry in maven metadata

---

Dockerfile
docs/types-and-platforms/mod-platforms/curseforge.md
docs/types-and-platforms/server-types/forge.md
examples/neoforge/docker-compose.yml

- pulls in https://github.com/itzg/mc-image-helper/pull/370
- pulls in https://github.com/itzg/mc-image-helper/pull/369
- resolves #2558

neoforge: support 1.20.2+

---

scripts/start-deployMagmaMaintained

handle different url of magma maintained 1.12.2

---

scripts/start-finalExec

Handle calculated MEMORY value along with Aikar's flags

---

docs/types-and-platforms/mod-platforms/auto-curseforge.md
examples/auto-cf/modpack-manifest/docker-compose.yml
examples/auto-cf/modpack-manifest/manifests/manifest.json
examples/auto-cf/using-excludes/docker-compose.yml

docs: added example of auto-cf custom manifest

---

examples/docker-compose-spiget.yml

Three times people have tried to rename this file 🤦‍♂️

docs: it’s spiget with an “e”

---

Dockerfile
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
examples/modrinth/local-modpack/docker-compose.yml

- Resolves https://github.com/itzg/docker-minecraft-server/issues/2144
- Resolves https://github.com/itzg/mc-image-helper/issues/376

Support local Modrinth modpack files

---

docs/misc/examples.md
examples/lazytainer/docker_compose.yml

According to the request from [Option to use lazymc](https://github.com/itzg/docker-minecraft-server/issues/2569#issuecomment-1873373665) I created an example docker_compose.yml and some description.

Added Lazytainer Example

---

scripts/start

umask as env var

---

docs/configuration/server-properties.md
docs/variables.md
examples/jline/docker-compose.yml

Identified [from Discord](https://discord.com/channels/660567679458869252/660569641550217327/1198689188900520036)

docs: clarify that disabling RCON disables other features

---

Dockerfile

modrinth: report error when project version not available for requested constraints

---

docs/versions/java.md
mkdocs.yml

There were two questions about this in Discord today
- https://discord.com/channels/660567679458869252/660567682751528981/1202380047516835880
- https://discord.com/channels/660567679458869252/660567682751528981/1202236505829941298

docs: clarified the Oracle GraalVM version used

---

examples/multi-project/servers/docker-compose.yml
examples/multi-project/servers/velocity-config/velocity.toml

Added multiserver Velocity preset since I saw many people asking to add velocity support but it was already added. People just don't read...

Added Velocity to Multi Server

---

.github/workflows/build-multiarch.yml
.github/workflows/verify-pr.yml
Dockerfile
tests/fulltests/multi-part-motd/docker-compose.yml
tests/fulltests/test.sh

Support 1.20.3 change to ping description structure

---

examples/paper-proxy-protocol/config/paper-global.yml
examples/paper-proxy-protocol/docker-compose.yml

Related to https://github.com/itzg/mc-router/pull/262

docs: add example of Paper running with PROXY protocol enabled

---

docs/configuration/misc-options.md

docs: clarify new default behavior with interactive console and colorized logs

---

docs/configuration/jvm-options.md

Helps https://github.com/itzg/docker-minecraft-server/issues/2626

docs: improve memory limit examples

---

Dockerfile
docs/types-and-platforms/mod-platforms/auto-curseforge.md
scripts/start-deployAutoCF

From [discussion in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1203840286200168608)
Pull in https://github.com/itzg/mc-image-helper/pull/388

auto-cf: provide option to force reinstall modpack's modloader

---

Dockerfile

Support NeoForge for Modrinth modpacks

---

scripts/start-finalExec
scripts/start-setupRbac

For legacy CURSEFORGE, write ops/whitelist files in final directory

---

Dockerfile

Related to #2647 
Pulls in https://github.com/itzg/mc-image-helper/pull/401

Improve rate limit detection and log available info

---

Dockerfile
scripts/start-deployBukkitSpigot

[Reported in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1208989217460322315)
Pulls in https://github.com/itzg/mc-image-helper/pull/403

Gracefully handle getbukkit.org outage when resolving version

---

Dockerfile
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
examples/bmc4/docker-compose.yml
scripts/start-deployModrinth

modrinth: add MODRINTH_OVERRIDES_EXCLUSIONS option

---

scripts/start-configuration
scripts/start-utils

Remove Java 8 warning and 5 second delay

---

Dockerfile

Supports new EC-based key exchange for SSH console.

Update to latest mc-server-runner

---

docs/types-and-platforms/server-types/hybrids.md

https://github.com/magmamaintained/Magma-1.20.1

Magma Maintained 1.20.1 is archived

---

examples/docker-compose.yml
examples/spigot/docker-compose.yml
scripts/start-deployBukkitSpigot

Fallback to existing server file when getbukkit retrieval fails

---

docs/types-and-platforms/server-types/bukkit-spigot.md

docs: add warning that GetBukkit is dead

---

files/auto/autopause-daemon.sh
files/auto/resume.sh

Removed write to /var/log/knocked-source during autopause resume

---

Dockerfile
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md

modrinth: fixed force include option

---

build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Also created a dummy gitconfig file at /etc/gitconfig so it does not need to be manually set at runtime

Add git-lfs package

---

docs/versions/java.md

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1231283124860616866)

docs: clarify the mention of java8 in deprecated section

---

docs/versions/java.md

Mentioned in https://github.com/itzg/docker-minecraft-server/discussions/2755#discussioncomment-9215531

docs: corrected mention of armv7 for latest/stable

---

files/auto/autopause-daemon.sh

 Apply SKIP_SUDO when starting knockd

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/420

paper: version metadata is optional for custom server jar

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/421

cf-files: correctly handle duplicate file refs

---

docs/misc/autopause-autostop/autopause.md

docs: added more detail about autopauase rootless usage

---

examples/bmc4/docker-compose.yml
examples/docker-compose-mods-mount.yml

examples: updated bmc4 example

---

Dockerfile

For https://github.com/itzg/rcon-cli/pull/57

build: upgrade rcon-cli and easy-add

---

scripts/start-utils

Fixed internal SPIGOT family mapping

---

docs/mods-and-plugins/index.md

Added a missing quotation mark I spotted while reading the documentation.
Thanks for the great work!

Added a missing quotation mark

---

Dockerfile

cf: allow for trailing slash on CF modpack page URL

---

build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Missed commits from https://github.com/itzg/docker-minecraft-server/pull/2835

build: upgrading git-lfs from packagecloud

---

scripts/start-setupServerProperties

Remove normalizing to uppercase of LEVEL_TYPE

---

examples/rad2/compose.yaml

I created a compose example for Roguelike Adventures and Dungeons with the proper excludes earlier for my server then reformatted it like the auto-cf example available in case anyone wants to use it for their own server. This is for the most recent version of RAD 2 1.11, it may require more excludes in the future.

rad2 compose example

---

mkdocs.yml

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1246937623508029461)

docs: allow for toggling light/dark mode

---

bin/mc-health
docs/configuration/misc-options.md
files/auto/autopause-fcns.sh

Added a variable for mc-monitor to recognize other addresses if network mode is host

Add SERVER_HOST Environment in mc-monitor command

---

scripts/start-deployPaper

From collaboration [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1249045449961111552)

paper: download default configs to allow for patching

---

Dockerfile

For https://github.com/itzg/docker-minecraft-server/issues/2865
Pulls in https://github.com/itzg/mc-image-helper/pull/435

cf: verify mod file hashes and re-download to repair

---

scripts/start-deployPaper

Resolves #2894
Caused by #2883

Disable default configs download until issues resolved

---

scripts/start-utils

Accept yes/no for boolean environment variables

---

.github/workflows/build-multiarch.yml
docs/versions/java.md

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1251237754856280234)

build: add java21-jdk variant

---

docs/mods-and-plugins/index.md

PR #2334 moved and renamed the compose file reference. This PR adjusts sources to changes.

Update compose file reference

---

files/cf-exclude-include.json

- Apple Skin
- Better Third Person
- Better F3
- Better Advancements
- Falling Leaves
- Searchables
- Visuality

Update cf-exclude-include.json with Apple Skin, etc

---

Dockerfile

cf: add support for modpacks that use NeoForge

---

files/cf-exclude-include.json

[From Discord](https://discord.com/channels/660567679458869252/660569755320844308/1258458440209006644)

Add ryoamiclights to CF global excludes

---

Dockerfile

cf: check downloads repo before attempting download of mod in modpack

---

Dockerfile

cf: copy files found in downloads repo

---

Dockerfile

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1261810548161511444)
Pulls in https://github.com/itzg/mc-image-helper/pull/451

mcopy: support basic auth via URL

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/452
Follow up to #2989

Avoid logging userinfo from MODS/PLUGINS URLs

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/454

Re-download Modrinth projects based on modified time rather than filename existence

---

files/cf-exclude-include.json

For https://www.curseforge.com/minecraft/modpacks/bm-exosphere
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1263989546127855687)

auto-cf: added blur-forge to global excludes

---

build/ubuntu/install-packages.sh
build/ubuntu/setup-user.sh

Also removing webp since it increased image size from 830MB to 1.03GB

build: remove pre-installed ubuntu user for consistency

---

files/cf-exclude-include.json

Add itemphysic-lite to global exclude

Add itemphysic-lite to global exclude

---

docs/configuration/server-properties.md
scripts/start-setupRbac

Resolves #3039
Follow up to #3038

Default EXISTING_OPS_FILE and EXISTING_WHITELIST_FILE to SYNC_FILE_MERGE_LIST

---

Dockerfile

Resolves https://github.com/itzg/mc-image-helper/issues/463

cf-files: improve the logging of missing dependencies especially optional ones

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/469

modrinth: improve logging of non-applicable versions

---

examples/simple-voice-chat/fabric-compose.yaml
examples/simple-voice-chat/neoforge-compose.yaml
examples/simple-voice-chat/paper-compose.yaml

I thought these examples might be useful for some people. Let me know if you like the format, comments, and configuration of these. I was also generally thinking of cleaning up the examples. Do you have any thoughts about that?

Simple Voice Chat examples

---

Dockerfile

For
- https://github.com/itzg/easy-add/issues/35
- https://github.com/itzg/mc-monitor/issues/95

build: upgraded easy-add and mc-monitor

---

examples/bmc4/docker-compose.yml

examples: updated BMC4 for v32.5

---

scripts/start-deployFTBA

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1292497029804855307)
Used this for testing:
```yaml
services:
mc:
image: itzg/minecraft-server
environment:
EULA: true
TYPE: FTBA
FTB_MODPACK_ID: 124
FTB_MODPACK_VERSION_ID: 12458
MODRINTH_PROJECTS: torchmaster:21.0.1-alpha
```

For FTBA support extra mods with Modrinth/CurseForge

---

Dockerfile
docs/mods-and-plugins/modrinth.md
scripts/start-setupModpack

modrinth: support datapack retrieval

---

docs/misc/troubleshooting.md
scripts/start

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1295088244052070502)

Add SKIP_CHOWN_DATA to skip the "Changing ownership of /data"

---

Dockerfile

cf: gracefully handle corrupted API cache index

---

examples/ftb-evolution/compose.yaml

I'm not sure if I included too much information or too little. I could add a line about it applying to other modpacks as well, but it might be good enough to just be able to send this as an example when someone shows up with a similar issue.

add ftb-evolution example file

---

scripts/start-setupModpack

Correctly handle NeoForge CF modpacks also using CURSEFORGE_FILES

---

examples/atm10/docker-compose.yml

I'm already maintaining it locally, might as well share it.

Create ATM10 example

---

Dockerfile
tests/setuponlytests/vanillatweaks_file/docker-compose.yml
tests/setuponlytests/vanillatweaks_file/require.sh

Resolves #3140
Pulls in https://github.com/itzg/mc-image-helper/pull/489

modrinth: more info in error when dependency has no applicable files

---

scripts/start-deployCustom

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1309319181044551721)

Include processing of SPIGET_RESOURCES with TYPE=CUSTOM

---

scripts/start-finalExec

[Discussed in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1311792256910364733)

Correcting name of .mc-health.env file

---

files/cf-exclude-include.json

as per [this discord conversation](https://canary.discord.com/channels/660567679458869252/660569755320844308/1312105025396281366)
There weren't any other problematic mods for TheCrimsonDankr

add advancement plaques to cf exclusions

---

Dockerfile

cf: use fallback URL for curseforge files like modpack files

---

examples/ftba/compose.yml
scripts/start-deployFTBA

[Discussed in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1313442193934913600)

Switch FTBA to use https://api.feed-the-beast.com/v1

---

scripts/start-deployFTBA

Fix regression from https://github.com/itzg/docker-minecraft-server/pull/3174
Applies info from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6312#issuecomment-2516899020

Fixed new FTB installer args and manifest

---

scripts/start-deployFTBA

Fixes regression noted in https://github.com/itzg/docker-minecraft-server/pull/3176#issuecomment-2519276876

Re-install FTB if manifest is missing

---

scripts/start-deployPurpur

Fix syntax error in start-deployPurpur

---

docs/misc/autopause-autostop/autopause.md

Resolves https://github.com/itzg/docker-minecraft-server/issues/3187

Corrected examples link in autopause docs

---

docs/mods-and-plugins/modrinth.md

[From discussion in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1318646614365179914)

docs: clarified Modrinth support includes plugins and datapacks

---

docs/mods-and-plugins/modrinth.md

Clarify Modrinth URL structure in documentation

Clarify Modrinth URL structure in documentation

---

examples/craftoria/docker-compose.yml

https://www.curseforge.com/minecraft/modpacks/craftoria

Add example of Craftoria modpack

---

examples/vault-hunters-1-18-2/docker-compose.yml

removed client side mode item-highlighter
made CF_API_KEY property more consistent with other examples 
set image tag to java17 for compatibility

fix vault hunters example

---

scripts/start-deployPaper
scripts/start-setupEnvVariables
scripts/start-utils

Download default spigot.yml for PaperMC to top-level directory

---

examples/canyon/compose.yml
scripts/start-deployCanyon

Corrected calculation of Canyon download URL

---

build/alpine/install-packages.sh

Install tput for colorized logs on alpine images

---

docs/index.md
docs/types-and-platforms/server-types/paper.md

Related to https://github.com/itzg/docker-minecraft-server/discussions/3230

Added compose example snippets for Paper docs

---

examples/multiline-motd/docker-compose.yml
examples/skyfactory5/compose.yml
files/cf-exclude-include.json

Thanks to [discussion in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1325663620721414177)

Added example for skyfactory5

---

Dockerfile

For https://github.com/itzg/docker-minecraft-server/issues/3236
Pulls in https://github.com/itzg/mc-image-helper/pull/503

cf: gracefully handle invalid modpack manifest file

---

scripts/start-deployKetting

ketting: fixed launcher invocation

---

Dockerfile

Resolves #3252
Pulls in https://github.com/itzg/mc-image-helper/pull/508

cf: qualify mapping of excluded slug to mod IDs

---

Dockerfile

Resolves #3255
Pulls in https://github.com/itzg/mc-image-helper/pull/509

cf: handle spaces around commas for includes/excludes

---

README.md

For https://github.com/itzg/docker-minecraft-server/discussions/3262

Clarify java edition aspect

---

files/cf-exclude-include.json

Remove konkrete from cf-exclude-include

---

scripts/start-deployFTBA

https://github.com/itzg/docker-minecraft-server/issues/3311

Added fabric-server-launch.jar to variants FTBA

---

docs/mods-and-plugins/index.md
examples/fabric-cardboard/compose.yml
scripts/start-utils

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1337781972277137433)

Added USES_PLUGINS to allows /plugins use with hybrid mods

---

Dockerfile

For https://github.com/itzg/mc-image-helper/issues/530
Pulls in https://github.com/itzg/mc-image-helper/pull/531

Upgrade helper to 1.41.2

---

Dockerfile

Pulls in https://github.com/itzg/rcon-cli/pull/69

rcon-cli upgraded to support command history

---

docs/misc/autopause-autostop/autopause.md
docs/misc/autopause-autostop/autostop.md
examples/autopause/compose.yml
files/auto/autopause-fcns.sh

Hoping it helps with scenarios like #3358

Add AUTOPAUSE_STATUS_RETRY_LIMIT and AUTOPAUSE_STATUS_RETRY_INTERVAL

---

scripts/start

Fix SKIP_CHOWN_DATA

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/issues/542

fabric: retry loader version lookup

---

docs/mods-and-plugins/curseforge-files.md
docs/types-and-platforms/mod-platforms/auto-curseforge.md
docs/variables.md
scripts/start-deployAutoCF
scripts/start-setupModpack

Reopen #3388 with a correct branch and some fixes.
Additionally add same functionality for modpacks too. And update docs. https://github.com/itzg/docker-minecraft-server/pull/3388#issuecomment-2772300235

Add support of CF_API_KEY_FILE environment variable

---

docs/mods-and-plugins/curseforge-files.md
docs/types-and-platforms/mod-platforms/auto-curseforge.md
docs/variables.md
scripts/start-deployAutoCF
scripts/start-setupModpack

Reverts itzg/docker-minecraft-server#3396

Revert "Add support of CF_API_KEY_FILE environment variable"

---

.github/workflows/build-multiarch.yml
docs/versions/java.md

Add Java 24 image variants

---

.github/workflows/build-multiarch.yml

Corrected build entries for Java 24

---

tests/setuponlytests/auto_curseforge/docker-compose.yml

Was getting build failures with filename matcher approach.

Change auto_curseforge test to use CF_PAGE_URL

---

files/cf-exclude-include.json

cf: fix missing comma in cf-exclude-include.json

---

files/cf-exclude-include.json

Allow particular-reforged in Beyond-Depth since it's a 1.20.1 modpack

Added forceInclude for particular-reforged since it's MC 1.20.1

---

Dockerfile
bin/mc-send-to-console
docs/commands.md
files/auto/stop.sh
files/sudoers-mc

Remove all use of sudoers file

---

scripts/start-configuration

logError was missing new type: LEAF. Added.

Updated start-configuration

---

docs/types-and-platforms/server-types/hybrids.md
scripts/start-configuration
scripts/start-deployMohist

Should fix #3419  but have not tested it much yet

Add support for youer and banner

---

Dockerfile

Resolves https://github.com/itzg/mc-image-helper/issues/563
Pulls in
- https://github.com/itzg/mc-image-helper/pull/565
- https://github.com/itzg/mc-image-helper/pull/566

With patching, support comments in JSON and adding to arrays

---

Dockerfile

Bumped mc_helper_version from 1.42.0 to 1.42.1 in Dockerfile

Bump mc-helper ver in dockerfile

---

Dockerfile

Resolves https://github.com/itzg/mc-image-helper/issues/575
Pulls in https://github.com/itzg/mc-image-helper/pull/576

Fixed handling of results output when using custom paper URL

---

.github/workflows/build-multiarch.yml
Dockerfile

Resolves #3517
Pulls in https://github.com/itzg/mc-image-helper/pull/587

Use Paper's Fill v3 download API

---

docs/mods-and-plugins/modrinth.md
scripts/start-setupModpack
scripts/start-utils

When using a custom server, allow specifying MODRINTH_LOADER with MODRINTH_PROJECTS

---

Dockerfile
docs/types-and-platforms/server-types/paper.md
scripts/start-setupEnvVariables

Resolves https://github.com/itzg/mc-image-helper/issues/595

Quieter Paper/Bukkit default configs downloading

---

docs/Dockerfile

Upgrade dev mkdocs to Python 3.11

---

Dockerfile

For https://github.com/itzg/mc-image-helper/issues/603
Pulls in https://github.com/itzg/mc-image-helper/pull/604

modrinth: prioritize target loader when resolving project versions

---

Dockerfile
docs/mods-and-plugins/modrinth.md
examples/modrinth/version-from-modrinth-projects/compose.yml
scripts/start-configuration

Resolves https://github.com/itzg/docker-minecraft-server/issues/3577

Add VERSION_FROM_MODRINTH_PROJECTS

---

Dockerfile

Resolves https://github.com/itzg/mc-image-helper/issues/607
Resolves https://github.com/itzg/docker-minecraft-server/issues/3582
Resolves https://github.com/itzg/docker-minecraft-server/issues/3583

Update Forge promotions URL

---

Dockerfile
docs/types-and-platforms/server-types/forge.md

Pulls in https://github.com/itzg/mc-image-helper/pull/609

Forge promotions and maven repo URLs are configurable

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/610
Helps with #3593

Limit/config concurrent downloads for CF and Modrinth

---

docs/misc/healthcheck.md
examples/ftba/compose.yml
scripts/start-deployFTBA

Populate MODPACK_NAME and MODPACK_VERSION from FTB modpacks

---

Dockerfile

Helps debug https://github.com/itzg/docker-minecraft-server/issues/3591
Pulls in https://github.com/itzg/mc-image-helper/pull/611

Analyze CF_API_KEY key when auth failures

---

Dockerfile
scripts/start-deployModrinth

Resolves https://github.com/itzg/mc-image-helper/issues/612

Fixed VERSION_FROM_MODRINTH_PROJECTS when a project has a shorter list

---

Dockerfile

Set FETCH_USE_HTTP2 to false
Pulls in https://github.com/itzg/mc-image-helper/pull/621
Follow up to #3617

Provide option to disable HTTP/2 use

---

Dockerfile
files/modrinth-exclude-include.json

modrinth: fix force include handling of default-excluded project

---

scripts/start-finalExec

Reverts itzg/docker-minecraft-server#3642

Revert "move USE_AIKAR_FLAGS=TRUE into else block"

---

scripts/start-finalExec

That should fix this Issue: https://github.com/itzg/docker-minecraft-server/issues/3643

Add UnlockExperimentalVMOptions to MeowIce flags

---

scripts/start-finalExec

At some point I need to go thru the updated meowice flags and check if anything should be updated with G1GC and add ZGC ones, but this should be enough to get the flags to work as a minimum

Should fix USE_MEOWICE_FLAGS

---

Dockerfile

https://github.com/itzg/mc-server-runner/pull/127

deps: upgrade mc-server-runner 1.13.4 for CVE fixes

---

Dockerfile

Includes https://github.com/itzg/mc-image-helper/pull/647
Resolves #3672

paper: now applies channel and resolves stable by default

---

files/cf-exclude-include.json
files/modrinth-exclude-include.json

Add colorwheel and colorwheel-patcher to default excludes
