itzg/docker-minecraft-server

minecraft-server/Dockerfile

Single quotes don't work for VOLUME, but double quotes do.

minecraft-server: fixing quotes so volume will create correctly

---

minecraft-server/Dockerfile
minecraft-server/README.md
minecraft-server/start-minecraft.sh

- Allow world URLs to end in something other than .zip (fixes #50 )
- Some whitespace fixes (tabs->4space)
- Allow TYPE=SPIGOT and TYPE=BUKKIT.  Note that only version 1.8.8 is currently available.
- Rename directories for dimensions if TYPE=SPIGOT/BUKKIT
- Some text changes to reflect new features
- Allow type options to be lower-case
- Add documentation
- Add /plugins mount for external bukkit plugins (like /mods for forge mods)

Add Spigot support, and non-zip URLs

---

minecraft-server/start-minecraft.sh

I wanted to ensure that certain "/gamerule" settings were established on server startup. I made a simple change to feed in a gamerules.txt file in start-minecraft.sh, if the file is found in the /data directory.

Adding gamerule.txt configuration file handling (optional)

---

minecraft-server/start-minecraft.sh

Using this code, wget will download and overwrite spigot_server.jar if and ONLY if it can contact the server and download a copy. otherwise, it will leave the file alone. If -O was used, wget would overwrite the file with 0 bytes, effectively deleting it. In combination with -N and double pipe, bash will skip to the next statement if the first returns false or an error.

[mc] resolved issues with downloading new server executable

---

elasticsearch/start

- modified the su CMD so that root's environment, which includes passed container variables, is passed to the elasticsearch user.
- modified the ordering of OPTS a bit so that --path.plugins is always last

fixed env inheritance issue, re-ordered OPTS

---

minecraft-server/README.md
minecraft-server/start-minecraft.sh

Hey,
I went ahead and added support for PaperSpigot as possible Minecraft Server (PaperSpigot is drop-in replacement for Spigot, so not many changes were required). It sure needs improvement (like better version handling).
Fixes #96
Really like your work here, cheers!

Add support for PAPER as possible Minecraft server

---

minecraft-server/docker-compose.yml

docker-compose refuses to build a container without the quotation marks.

minecraft-server: EULA var needs to be a string (docker-compose.yml)

---

minecraft-server/README.md

This fixes the formatting of `minecraft-server`'s README file for two `docker run` commands.

Fix formatting in minecraft README

---

minecraft-server/start-minecraft.sh

This fixes an error caused by the expired certificate on http://ci.mcadmin.net.
I know it's a sub-optimal solution but I can't see another solution until http://ci.mcadmin.net sorts out their certificate.

Use cURL insecurely when downloading

---

minecraft-server/start-minecraft.sh

If set via ENV, disable GUI on server.
Test script:
```
#! /bin/bash
CONSOLE=true
GUI=false
EXTRA_ARGS=""
if [[ ${CONSOLE} = false ]]; then
EXTRA_ARGS+="--noconsole"
fi
if [[ ${GUI} = false ]]; then
EXTRA_ARGS="${EXTRA_ARGS} nogui"
fi 
echo $EXTRA_ARGS 
```
```
+ CONSOLE=false
+ GUI=false
+ EXTRA_ARGS=
+ [[ false = false ]]
+ EXTRA_ARGS+=--noconsole
+ [[ false = false ]]
+ EXTRA_ARGS='--noconsole nogui'
+ echo --noconsole nogui
--noconsole nogui
```
```
+ CONSOLE=true
+ GUI=false
+ EXTRA_ARGS=
+ [[ true = false ]]
+ [[ false = false ]]
+ EXTRA_ARGS=' nogui'
+ echo nogui
nogui
```
```
+ CONSOLE=true
+ GUI=true
+ EXTRA_ARGS=
+ [[ true = false ]]
+ [[ true = false ]]
+ echo
```

Add optional `nogui`

---

minecraft-server/start-minecraft.sh

First of all: Thanks for your minecraft-server image, I really like it 👍 
* Fixed FORGEVERSION in case statement to working FORGE_VERSION
* Removed default case because `FORGE_VERSION=$FORGE_VERSION` doesn't make a lot of sense if nothing needs to be changed.
* Add support for BIOMESOP level-type

minecraft-server: Fixed FORGEVERSION case, add support for BIOMESOP

---

minecraft-server/start-minecraft.sh

Env variable `SPAWN_ANIMALS` was misspelled as `SPAWN_ANIMAILS`, thus rendering the modification of this option in the config file from env variables non effective if the documentation is correctly followed.
Also, `spawn-npcs` was repeated two times.
Also, `force-gamemode` was never taken into account because of a regex issue.

Fix typos in config file generation

---

minecraft-server/README.md
minecraft-server/start-minecraft.sh

When the option `MODPACK` is specifed you can also instruct script to delete old mods/plugins prior to installing new ones.
This behaviour is desirable in case you want to upgrade or replace mods/plugins from downloaded zip file.

Added option REMOVE_OLD_MODS

---

minecraft-server/start-deployFTB

The core of this pr allows a user to backup and restore only their world save rather than the whole minecraft data folder.

Allow existing world volume mount for FTB

---

minecraft-server/start-finalSetup04ServerProperties

Env variable `MAX_TICK_TIME` didn't work because of this typos in property name.

Fix typos in config file generation for max-tick-time setting.

---

minecraft-server/start-finalSetup01World

Unzipping world
replace banned-ips.json? [y]es, [n]o, [A]ll, [N]one, [r]ename:
unzip: can't read standard input

unzip fails if a file already exists in the zip file.

---

minecraft-server/start-deployFTB

We have pushd'ed into the directory so do not prefix the shell script
with the directory name.

mc: run FTB installer from correct location

---

minecraft-server/start-minecraftFinalSetup

The -z argument was only matching if there were no json files. Adding ! in front so it matches correctly and replaced ls with find to provide more consistent matching.
Addresses #89

using find to match json files

---

minecraft-server/Dockerfile
minecraft-server/start-minecraftFinalSetup

Deep copy any *.jar files in /plugins and update the corresponding files in the /data/plugins dir.
The goal of this PR is to allow updating of plugins through child Docker images.
If wanted this can also be implemented for the /mods dir. May workaround implementing #267 and  #218

feat(minecraft-server): update spigot plugins using /plugins if newer

---

minecraft-server/README.md
minecraft-server/start-finalSetup02Modpack

If you use something like curseforge, you may end up creating/using modpacks that do not
contain server mod jars. Instead, the curseforge setup has `manifest.json` files, which
will show up under `/data/FeedTheBeast/manifest.json`.
To use these packs you will need to:
- Specify the manifest location with env var `MANIFEST=/data/FeedTheBeast/manifest`
- Pick a relevant ServerStart.sh and potentially settings.cfg and put them in `/data/FeedTheBeast`
An example of the latter would be to use https://github.com/AllTheMods/Server-Scripts
There, you'll find that all you have to do is put ServerStart.sh and settings.cfg into
`/data/FeedTheBeast`, taking care to update settings.cfg to specify your desired version
of minecraft and forge. You can do this in the cli with something like:
```
$ wget …
```

Fix #287 : Support manifest.json

---

minecraft-server/start-finalSetup02Modpack

This is sort of a combo fix.
For one, it appears some modpacks have been generated without a 'mods' dir, so running the manifest download will fail without a 'mkdir'. This appears to just be a thing that happens with the newest modpacks.
There's also an issue with the jq expression where slurping and stdin syntax differ (the dollar sign shouldn't be used).

Fix for custom curseforge modpacks that do not have mods dir

---

minecraft-server/start-deployPaper

There were some small changes done to PaperMc's CI urls for older versions of minecraft.

Updated PAPERMC CI URL and job name for older versions

---

minecraft-server/start-finalSetup04ServerProperties

As discussed in #204 
This was motivated by the game-server-operator minecraft deployment logic, where we map a custom Kubernetes resource to a Minecraft instance. Ideally users would be able to change the Minecraft resource and have the deployed server configuration change to reflect this.
This only handles `server.properties` related environment variables, and doesn't resolve the mods-related variables (because I don't understand how minecraft modding works well enough to do that with confidence). It also doesn't handle ops/whitelist variables, I wasn't sure if I should make a broader `OVERRIDE_CONFIGURATION` and get rid of `OVERRIDE_SERVER_PROPERTIES`, or if it would be better to have more granular `OVERRIDE_OPS` + `OVERRIDE_WHITELIST` (maybe in addition to a general …

Allow user to specify that server properties be overridden on start

---

minecraft-server/README.md
minecraft-server/start-deployBukkitSpigot
minecraft-server/start-deployCustom
minecraft-server/start-deployPaper
minecraft-server/start-deploySpongeVanilla
minecraft-server/start-deployVanilla

This may partially (or fully?) resolve #198 
In some scenarios, it is not ideal to manually delete the server .jar file in order to force minecraft-server to download a fresh copy.  For situations when a new version of minecraft is released and there is steady incremental fixes made to the server type, there are new versions of the server created multiple times a day (e.g. [the 81 builds of the paper server since 1.14 was releases](https://papermc.io/downloads#Paper-1.14)).  
The option added in this PR gives server operators the option to have minecraft-server automatically download a fresh, (most likely) updated copy of the server for that particular release of minecraft.

add option for force re-download of server file

---

minecraft-server/Dockerfile

To have the java 8 properly take account for available memory usage available to the container.
https://blog.softwaremill.com/docker-support-in-new-java-8-finally-fd595df0ca54

Change to 8u212

---

minecraft-server/start-finalSetup02Modpack

This allows for links such as https://dev.bukkit.org/projects/multiverse-core/files/2729939/download to work in the MOD fields.
I've been able to test the MODS implementation but not MODPACK and Manifest. If somebody could fire a test in there that would be great.
This closes #345

Support HTTP redirects in modpack URLS

---

start-deployFabric

Fabric's installer uses `-mcversion` to specify the Minecraft version (https://fabricmc.net/wiki/install). The way the command is written right now it will always use the latest version of MC and ignore the `VERSION` specification.
See https://github.com/itzg/docker-minecraft-server/issues/351 for more discussion.

Fix -version => -mcversion

---

start-minecraftFinalSetup

Update start-minecraftFinalSetup to remove typo in sed command

---

start-finalSetup02Modpack

`CURSE_URL_BASE` already had `/projects` appended to it, missed it by mistake. Originally wrote `redirect_url` assuming `CURSE_URL_BASE` was `https://minecraft.curseforge.com`

fix duplicate projects subpath

---

start-configuration

When you for example set the `EULA` environment variable to `true` (instead of uppercase `TRUE`) the `eula.txt` is written with a wrong value and the server won't start. After that, it is not possible to change the value using the `EULA` environment variable and you would have to change the file manually, which might be a little complicated for some users when they use docker volumes instead of bind mounts.
This pull request fixes this by checking the value to be `TRUE` (uppercase) before writing the `eula.txt` file. For any other value, the request to set the value using `-e EULA=TRUE` is displayed.

Only write EULA when it's set to `TRUE`

---

start-minecraftFinalSetup

Creation of settings-local.sh for FTB instances does not propagate JVM_XX_OPTS and JVM_OPTS into the file, leading to those instances ignoring those parameters.  This fix adds those to the exported JAVA_PARAMETERS env var, which should have the desired effect.

Fixed JVM_XX_OPTS for FTB servers

---

Dockerfile

Changes:
- Added the `--start-period=5m` option to the docker healthcheck which offsets the mcstatus commands by 5 minutes to allow modpacks to complete downloading.

(improvement) Offsets healthcheck to T+1m

---

docker-versions-create.sh

I've created a small sh script to simplify docker container creation with version.
Hope it will speedup [#360 ](https://github.com/itzg/docker-minecraft-server/issues/360) issue resolution. 
I've tested it to the point of actual pushes. As I don't know the environment configuration of your workstation - I assume the script to be changed to work in your environment. 
Upon completion you need to do some manual steps:
1. Merge github branch that the script created
2. Update docker hub description and add new version with link to a dockerfile that was created by this script.

docker-versions-create init

---

start-finalSetup02Modpack
start-utils

Pull request to address issue #413 
Feel free to push back if you don't like the changes. 
* In my changes, I renamed the MANIFEST_URL variable to be MANIFEST_FILE for the block of code that handles the manifest file.
* I first check if the supplied ENV variable MANIFEST is an existing file, and use that.
* Next check is if the supplied MANIFEST is a url.  If so, use curl to download remote manifest.json file and save to /tmp, and use that file for MANIFEST_FILE.
* Last "check" is the else - to catch if it wasn't an existing file and not a URL.  I display a message but chose not to exit/fail because I didn't know if that would break anything else.  It could probably use an exit between lines 87-88.
I also fixed what I believe is a bug in the start-utils isURL function since my changes are …

Better handle CurseForge manifest.json

---

start-finalSetup04ServerProperties

Needed when your machine has multiple ip adresses assigned and you want to host your server on only one ip instead of allocating all available ips.

Allow to modify server-ip in server.properties

---

start-finalSetup02Modpack

As discussed on Gitter, this commit changes the GENERIC_PACK feature to keep track of added files in a `manifest.txt` so that in the event of a change to the generic pack, the older version can be cleaned up to allow for the new pack to be introduced without older files causing issues.

Enable upgrades with GENERIC_PACK

---

README.md
start-deployPaper
start-finalSetup04ServerProperties

Hello,
This PR add environnent variable `PAPERBUILD` (default to `latest`) to specify wich paper build want download.
This PR also remove legacy usage of numeric `gamemode` and `difficulty`. From 1.14 this is legacy (source: https://minecraft.gamepedia.com/Java_Edition_18w48a)
Thanks

Allow specify paper build  and don't use legacy gamemode and difficulty

---

server.properties

The `sed` command in
https://github.com/itzg/docker-minecraft-server/blob/master/start-finalSetup04ServerProperties#L16
does nothing if the line is not already in the file.
> [09:14:03] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.

Add `resource-pack-sha1` to server.properties

---

start-deployBukkitSpigot

This hotfix helps with the different behaviour of BuildTools.jar in 1.14 and above. It's a bit sketchy, but without it, this docker is unusable with Spigot 1.14 or newer right now.

Short hotfix until version helper function is done

---

start-minecraftFinalSetup

Some flags were adjusted according to the changelog at https://mcflags.emc.gs:
> 5/2/2020: Added +PerfDisableSharedMem, Adjusted MixedGCTarget to 4
> 4/25/2020: Removed OmitStackTraces since it could cause performance issues with some plugins (but not everyone)

Update Aikar flags as of 5/2/2020

---

files/autopause/autopause-daemon.sh
files/autopause/pause.sh
files/autopause/resume.sh
start
start-utils

The redirection is not necessary and might be the cause to reported problems. Also wrapping the logging to corresponding functions

Autopause logs

---

start-autopause
start-configuration

@Oekn5w, looking again at `start-configuration` it seemed like it would be good to refactor the setup code for autopause into its own file to ease maintainability. Can you double check the refactoring for me?

Refactored autopause setup into its own start-file

---

Dockerfile

Some Spigot plugins (namely BannerBoard and InteractiveBoard that I've tested) use the Java2D graphics library to render in-game maps from images, text, etc. server side. Unfortunately Java2D will crash if it can't find at least one system font when it calls sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames() causing any plugin that uses this API to fail to load.
This isn't a problem on most systems as almost every distro's openJRE package marks fontconfig or dejavu as a dependency to prevent issues like this, however openJDK's alpine images don't for some reason (presumably  because you wouldn't normally need font access in a headless environment except for extreme edge cases).
This change simply adds ttf-dejavu to the APK list which solves this issue for both of these …

Add ttf-dejavu to package list

---

start-finalSetup01World

FTB modpacks that have a top-level directory named for the modpack will result in extracted and cloned world data landing in the wrong location. This is fixed by extracting FTB worlds to FTB_DIR which is set during start-deployFTB.

Updated worldDest to use FTB_DIR

---

start-minecraftFinalSetup

server-icon.png does not correctly get copied to the FTB directory when using FTB/CurseForge modpacks

Move server-icon.png to FTB_DIR if exists

---

README.md
start-finalSetupWorld

Setting `FORCE_WORLD_COPY=TRUE` will overwrite the world on server start.

Added 'FORCE_WORLD_COPY' environment variable

---

README.md
start-finalSetupEnvVariables
start-utils

Using the -prune option to exclude paths in "find" should be a lot more efficient than -not since it prevents find from traversing excluded directories / files.

Use -prune for "REPLACE_ENV_VARIABLES_EXCLUDE_PATHS" feature.

---

README.md
start-finalSetupEnvVariables

Turns out there were multiple issues with how we constructed the find command when using directory excludes. This led to the find command not replacing any configurations when `REPLACE_ENV_VARIABLES_EXCLUDE_PATHS` was set.
This is the configuration in which I got it working. Tested it locally with directories with 2000+ files. The speedup is really good :slightly_smiling_face:.
I'm not an expert on bash or the find command so please let me know if there are issues with the patch.

Fixed "REPLACE_ENV_VARIABLES_EXCLUDE_PATHS" breaking cfg replacer when set

---

README.md

most people will start with the quickstart command, which won't work anymore now that EULA is required.  Modified the sample quickstart to include the new minimum params.

Adds EULA to the 'quickstart' command in readme

---

README.md

Adds a bit more info about the configuration options available when using a persistent mount and an example of how this allows one to change `server.properties` including specifying which map to use.
**Note: ** I could not actually figure out the syntax of how to specify a shared folder, with a premade map, and how to use that on first-launch.

Added note on tweaking settings and using own map

---

files/autopause/autopause-fcns.sh

The AutoPause Feature currently only supports IPv4, this PR fixes just that. Tested and working as expected on a GCP Server. The regex for matching loopback addresses was taken from [Stackoverflow](https://stackoverflow.com/a/8426365/6500551), seems to work just fine, but I also manually checked some edge cases

IPv6 support for autopause

---

Dockerfile

This changes the base image to the one from AdoptOpenJDK's latest JDK (they don't provide a tag for 'JRE-latest'). AdoptOpenJDK is currently at 15.x, which includes Shenandoah GC and other improvements, and is based on Ubuntu images just like the 'multiarch' image is.
I'll issue some PRs for other changes that actually make use of the new features shortly.

Convert to AdoptOpenJDK

---

Dockerfile

We don't need Java 8 from Ubuntu, we have 15 from AdoptOpenJDK.

Remove distro-provided JRE

---

start-finalSetupWorld

Spigot worlds were incorrectly identified as multiple worlds and when copying the worlds the code would not copy the nether and end properly. This change will hide the nether and end worlds from the multiple world search and also copy the nether and end if it exists.
There is existing code that I thought did the latter on first glance, but it is actually to convert a world *to* a spigot world only.
Fixes #682

Fixing some spigot world import issues

---

README.md
start-finalSetupModpack
start-minecraftFinalSetup

A `REMOVE_OLD_MODS_INCLUDE`, `REMOVE_OLD_MODS_EXCLUDE` and `REMOVE_OLD_MODS_DEPTH` option can now be specified to filter the plugins or mods that should be deleted.
`REMOVE_OLD_MODS_INCLUDE` defaults to `*` which mirrors the current behauvior of deleting everything inside the `plugins` or `mods` directory.
Closes #662

feat: improve REMOVE_OLD_MODS option

---

README.md
start-minecraftFinalSetup

A new `COPY_CONFIG_DEST` option now allows you to specifcy where the files in `/config` should be copied to.
Defaults to `/data/config` to mirror the old behaviour.
Closes feat: copy server configs into server dir (analogue to bungee) #664

feat: add COPY_CONFIG_DEST option

---

start-deployFTBA

For some reason ftb-installer puts more than one entry into the targets
array for "forge" which screws up the filename we expect for the
installed server.  I saw this only with some modpaks and not others
(eg FTB_MODPACK_ID=23 this happens, but not FTB_MODPACK_ID=31)

ignore duplicate entries in the targets array of version.json

---

start-finalSetupServerProperties

@P4sca1 I was going to suggest this change, but was just as easy to make the change and PR it.
Fixes #446

Escaped backslashes when setting server property value

---

Dockerfile
files/autopause/autopause-daemon.sh
files/autopause/autopause-fcns.sh
files/autopause/knockd-config.cfg
files/autopause/pause.sh
files/autopause/resume.sh
files/sudoers-mc
health.sh

Adding net-tools, replacing killall with pkill, and replacing ps -a with ps -ax

Fixing AUTOPAUSE on Raspberry Pi 4s

---

README.md

Fix the typo in the `README.md`, docker volumes in docker-compose yaml should be in the list format.

Fix README: volumes should be in list

---

examples/docker-compose-simple.yml

After copy pasting the docker-compose error occured:
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mc.volumes contains an invalid type, it should be an array
I've just add "-" and should work now.

Fix typo in example docker-compose

---

README.md
start-finalSetupMounts

Using curseforge modpacks creates a FeedTheBeast folder in /data which contains the /mods folder, this env variable would allow to copy mods to that folder properly.

COPY_MODS_DEST env variable 

---

start-finalSetupModpack
start-utils

Since `curl` can natively download files from FTP servers, given a `ftp://` URL, support those URLs. Closes #849

Support FTP servers for file downloads

---

start-deployCF

The deployCF script looks for `forge*.jar`, which can match mods with
"forge" in the name (e.g.
https://www.curseforge.com/minecraft/mc-mods/forgery). This change
allows the mod to work as-is without renaming it to
`forg_ery-1.2.3.jar`.
Here's how it didn't work before (both forge and forgery are found):
```
mc_1      | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    3 1000     1000             7 Apr 30 18:04 /data'
mc_1      | [init] Resolved version given 1.16.5 into 1.16.5
mc_1      | [init] Resolving type given CURSEFORGE
mc_1      | [init] **********************************************************************
mc_1      | [init] WARNING: The image tag itzg/minecraft-server:java8 is recommended
mc_1      | [init]          since some mods require Java 8
mc_1      | …
```

allow mods with "forge" in name for cf modpacks

---

README.md
start-finalSetupModpack

I noticed while testing some things with this image that local paths were available for using Worlds, but not for Mods or Modpacks.
I spent a little bit of time trying to implement this in my own branch, and think it would be useful upstream.
I understand that the usecase can also be served through utilising volumes, however having similar functionality for these environment variables may aid usability.
I'm also unsure whether the checking of paths is sufficient - this will check whether a path ends in the correct extension right now, but not much more - although we do also check whether the command succeeds.

Support local paths for modpacks / mods

---

examples/modpacks/README.md

SF 4.1.0 doesn't work with the latest Forge anymore. 4.2.2 does.

fix: update Sky Factory version link

---

start-deployCF

After working w/ a CurseForge mod, I tracked down a bug in the find statement that when the forge server is in */FeedTheBeast/mods/forge-<version>.jar, the find statement to locate it won't actually work due to the path */mods/*. Removed the leading * (also from the * in front of libraries) and added in a maxdepth (forge installer will also make a copy in /libraries/net/minecraftforge/forge/<version>/).

fix bad find statement

---

README.md
start-deployAirplane

This PR enables the use of Airplane on Java versions above 11, in anticipation of 1.17.

Support Java versions above 11 for Airplane

---

start-deployYatopia

api.yatopiamc.org/v2/stableBuild API has been broken for a couple of months (see https://github.com/YatopiaMC/Yatopia/issues/488 ) and it looks like it won't be fixed soon. Thus, changed the default RELEASE value from stable to latest, so that Yatopia can still be easily set up without explicitly specifying a RELEASE env.

Workaround: Change default RELEASE of Yatopia

---

start-deployFTBA

Fabric FTB packs don't currently work; they install successfully, but fail to launch because `start-deployFTBA` doesn't recognize the jar filename format. This patch adds the Fabric jar filename format to the candidates to launch.
Fixes #912

Modify start-deployFTBA to allow Fabric FTB packs

---

README.md
start-deployAirplane

This PR reflects Airplane's move to their new Jenkins-based download system. It also enables support for 1.17, as well as the new Airplane+Purpur branch.

Move to new Airplane download system

---

README.md
start-finalSetupServerProperties
start-minecraftFinalSetup

Currently there is no way to just enable the whitelist without adding a player to the whitelist file.
This change allows to set `WHITELIST=true` to set the server properties accordingly without modifying the whitelist file.
Players can then be added / removed from the whitelist using the `whitelist add` and `whitelist remove` commands.
For convenience `WHITELIST=false` will now disable the whitelist and has the same behaviour like `WHITELIST=` (empty string).
Signed-off-by: Pascal Sthamer <sthamer.pascal@gmail.com>

Allow to enable the whitelist without modifying the whitelist file

---

start-finalSetupServerProperties

Using `sed`, we need to escape backslashes, but with `echo` we can just use the variable as-is.
Closes #949

fix: don't echo double backslashes to server.properties

---

README.md

Figured this was the cleanest way to format it, but am open to suggestions.

Update README with watchdog disable option for autopause on Paper servers

---

README.md
start-deployAirplane

This PR updates the Airplane branch names for the 1.17/1.17.1 release. The branch was named 1.17.1 for a short while, but was reverted back for consistency.

Update Airplane branches for 1.17 release

---

start-spiget

implemented to only re-download SPIGET resources with REMOVE_OLD_MODS enabled
fixes #974 partially
todo:
^ todos not needed because getting the timestamps from the API also might rate limit.

fix: SPIGET_RESOURCES not always download

---

start-deployFTBA

this should fix #773 
detect if we're running on ARM and switch to downloading the ARM FTB installer
not tested yet (other than confirming the FTB installer works on ARM)

detect and download ARM installer if needed

---

README.md

Tuinity has recently been discontinued and adopted by the Paper project. This means that Tuinity is no longer necessary.

Remove tuinity section from README.md

---

start-setupModpack

I ran into this bug when trying to use the MODPACK envar. Example log:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 9 1000 1000 4096 Sep 24 04:41 /data'
[init] Resolved version given latest into 1.17.1
[init] Resolving type given FABRIC
curl: unknown --write-out variable: 'effective_url'
[init] ERROR Invalid URL given for MODPACK:  resolved from https://gitlab.com/avionix/minecraft-mods/-/jobs/artifacts/master/raw/ueg-modpack-server.zip?job=ueg
[init]       Must be HTTP, HTTPS or FTP and a ZIP file
```
It seems to be a one-line fix (a typo in a curl variable). I've tested the fix locally and it works as expected.

Fix 'curl: unknown --write-out variable' for .zip modpacks

---

Dockerfile
examples/docker-compose-autopause.yml
files/autopause/autopause-fcns.sh

Image is available for testing `itzg/minecraft-server:test-auto-pause-use-mc-monitor`
cc @Oekn5w @kjburr 
Closes #1046

For autopause, added use of mc-monitor to detect players connected

---

README.md

because while experimenting with RCON, it's highly confusing why without a RCON_PASSWORD it happens
to "just work" e.g. with https://github.com/willroberts/minecraft-client (which uses "minecraft" as the default password itself!)
but not with https://github.com/itzg/rcon-cli (which has no default password).
Default passwords are always a bad idea, and should ideally ideally just be removed (if you are willing to make that backward compatible breaking change).

document that default RCON_PASSWORD = minecraft in README

---

README.md

Replace broken https://mcflags.emc.gs with
https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
which presumably was the original where that came from.

Docs: Fix broken link to Aikar's Flags

---

README.md
scripts/start-finalExec

- Added a check to see if WHITELIST contains a "-", if it does then parse it as a list of UUIDs rather than normal Usernames
NOTE: It's a crude fix and I am by no means good at bash. I just wanted to give it a shot.

Whitelist UUID Support

---

README.md
scripts/start-setupServerProperties

I've added a `server.properties` override for the 'require-resource-pack' option, to allow server operators to set this in tandem with the other resource pack options.
As an additional change, I've removed the details around escaping requirements, as this is now handled with the setServerPropValue function.
- Add server.properties override for 'require-resource-pack'
- Removed escape requirement note

Feature: Enforcing resource packs

---

scripts/start-deployBukkitSpigot

The previous logic attempted to download craftbukkit from [1]. This resulted in a 404.
This commit adjusts this logic and uses the alternative download site at [2].
[1]: https://download.getbukkit.org/craftbukkit/craftbukkit-1.16.5.jar
[2]: https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.16.5.jar
---
```bash
docker run --rm -it -e EULA=true -e TYPE=craftbukkit -e VERSION=1.16.5 itzg/minecraft-server:java8
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Nov 24 20:37 /data'
[init] Resolved version given 1.16.5 into 1.16.5
[init] Resolving type given craftbukkit
[init] Downloading CraftBukkit from https://download.getbukkit.org/craftbukkit/craftbukkit-1.16.5.jar ...
curl: (22) The requested URL returned error: 404 Not Found
```
```bash …
```

Fix downloading of craftbukkit when using 1.16.5

---

README.md
scripts/start-setupModpack

See https://packwiz.infra.link/ for packwiz information
This PR adds support for packwiz server modpack definitions provided via the `PACKWIZ_URL` environment variable.
Packwiz modpack definitions are processed before other mod definitions (`MODPACK`, `MODS`, etc.) to allow for additional processing/overrides the operator may want to perform (in case of mods not available via Modrinth/CurseForge, or where the pack is not maintained by the operator).
We attempt to retrieve the latest bootstrap jar from Github if it doesn't already exist. If for any reason retrieving release information from Github isn't possible, we'll use the existing bootstrap jar if already available.
Packwiz is pre-configured to show no GUI and only download server mods. A relevant note to `README.md` has been added to …

Implement support for packwiz modpacks

---

README.md

A small PR to improve the Fabric documentation in the Readme.
Changes:
* Move Fabric server instructions below Forge (as increasingly common server type configuration)
* Condensed Fabric setup instructions (specific loader more common than custom installer)
* Updated Forge notes to include Fabric where applicable
See commit messages for more details/rationale on changes.

Fabric documentation update

---

scripts/start-finalExec

It appears we missed this in our first patch @itzg.
I've ___not___ tested this, but it should be fine.

fix: log4j patch being applied to <1.7 versions

---

scripts/start-deployAirplane

Changes speak for itself, mostly. The script for Paper already does this, thought it'd be useful for Airplane too.

Remove old Airplane versions

---

README.md
scripts/start-configuration

Startup fail-fast if ENABLE_AUTOPAUSE=true && EXEC_DIRECTLY=true

---

README.md
scripts/start-finalExec
scripts/start-setupServerProperties

This PR implements a few notable changes to the handling of ops and whitelist configurations, including:
* Support for a preconfigured file (via `OPS_FILE` and `WHITELIST_FILE`)
* Extension of UUID support to `OPS` and better handling of mixed configurations
* Additional handling of txt/json generation in the vanilla 1.7.5 -> 1.7.6 jump (support for usernames & uuids in all server binaries)
Documentation has been updated to clarify the configuration options, and draw attention to the `ENFORCE_WHITELIST` variable (with a warning being added to the logs when whitelist is enabled but not enforced).
Detailed changes and rationale can be seen in the expanded commit messages.

Rework whitelist and ops support

---

Dockerfile

This removes any file-permission ambiguity that can result from a different umask set at git checkout
time on developer's or build machine.
This problem was noticed when running a `buildx` on MacOS with a `umask` set of `0077`.  Git doesn't do anything special with `rw` attributes, only `x`, so these are inherited from the checkout user's `umask`.  Since Docker passes these through, this seems to be a flaw in build-portability of Git Checkout -> Docker Build (same build args) -> Image.  So my image fails to run as `minecraft:minecraft` due mainly to missing group/world `r` permissions ... `x` that is added currently is not sufficient and will fail immediately with:
```
/bin/bash: /start-configuration: Permission denied
```
This PR adds `--chmod` to all `COPY` instructions in the …

Added --chmod to all COPY instructions in Dockerfile

---

scripts/start-finalExec

Using rolling logs previously prevented the CVE-2021-44228 mitigation from working.
This commit forbids rolling logs if required to prevent CVE-2021-44228.
This can be considered a hotfix.
See #1189

secruity: Fix CVE-2021-44228 mitigation

---

README.md
scripts/start-deployAirplane

This PR removes Airplane 1.16, as it is no longer supported or hosted.

Remove Airplane 1.16 as unsupported

---

scripts/start-spiget

I came across the issue that the downloaded resources was in fact some kind of html output. Looks like the download failed somehow (in my case the dynmap plugin (274).
Example:
http://api.spiget.org/v2/resources/274/download --> https://dev.bukkit.org/projects/dynmap/files/3561925
Sure ... the owner of dynmap is using a link that points to a webpage instead of the real download.
So the curl download generates a html output which gets saves to 274.jar ... which then creates errors when the server trys to load the plugin. At least we should verify that the downloaded .jar file is a valid minecraft plugin with `plugin.yml` in it.

fix: verify that the downloaded resource is a valid plugin

---

Dockerfile
README.md
examples/docker-compose-autostop.yml
files/autostop/autostop-daemon.sh
files/autostop/stop.sh
scripts/start-autostop
scripts/start-configuration
scripts/start-utils

implements #1211 according to Discord description.

Autostop feature

---

README.md
scripts/start-setupDatapack
scripts/start-setupWorld

Mostly copied from setupModpack script, downloads zip files into $LEVEL/datapacks.
Note that this currently does not handle custom world directories as the setupWorld script also doesn't handle it. Plus I would expect datapacks on Bukkit / derivative servers to be quite a niche case.
Implements #1152

Create datapack download script

---

README.md

I had problems with mc-status with autopause enabled and I don't want other people to struggle with the same issue 😎 Thanks for help with finding out what was the issue, @itzg 🎉

Add note about mc-status under autopause section

---

scripts/start-deployCF

Not the best at bash scripts but I thought this is a clean way to get this done

Support downloading CurseForge modpack when USE_MODPACK_START_SCRIPT is false

---

.github/workflows/build-multiarch.yml
.github/workflows/pr.yml
scripts/start-deployPurpur

fix[purpur]: use mc-image-helper for robust Purpur build lookup

---

examples/docker-compose-generic-pack.yml
scripts/start-setupModpack

fix: ensured GENERIC_PACKS are re-applied with REMOVE_OLD_MODS

---

README.md
scripts/start-configuration
scripts/start-deployAirplane
scripts/start-deployPufferfish

I hope I didn't forget anything.
Tested it locally with this docker-compose and it all seems to work:
```yaml
version: '3'
services:
mc:
build: .
environment:
EULA: true
TYPE: 'PUFFERFISH'
VERSION: 'LATEST'
PUFFERFISH_BUILD: '29'
```
I've also opened an issue on the Pufferfish repo to maybe clean up the .jar name a bit.
Closes #1226

Add Pufferfish support

---

README.md
scripts/start-setupServerProperties

fix(limbo): convert MOTD to JSON chat format

---

scripts/start-setupServerProperties

Fixes #1261 
`-v "$MOTD"` is used to check if a environment variable is unset, and returns 0 (FALSE) if the value is set.
Thank you to @Stealthii for identifying this issue.

fix: Set default MOTD if unset

---

README.md

This PR documents the Flare Flags variable, as the profiler is now available in [plugin](https://github.com/TECHNOVE/FlarePlugin) form. Also adds a note under Pufferfish, since it's built-in (Pufferfish re-implements part of Airplane's featureset for 1.18).

Docs: Flare flags

---

.github/workflows/build-multiarch.yml
scripts/start-deployAirplane
scripts/start-deployBukkitSpigot
scripts/start-deployCanyon
scripts/start-deployPaper
scripts/start-deployPufferfish
scripts/start-deployPurpur
scripts/start-finalExec
scripts/start-setupModconfig
scripts/start-setupModpack
scripts/start-setupMounts
scripts/start-setupWorld
scripts/start-utils

fix(purpur): apply log4j mitigations specific to Purpur

---

scripts/start-setupModpack

Was having issues with pulling the packwiz installer bootstrap and noticed that the repository has been changed from comp500/packwiz-installer-bootstrap to packwiz/packwiz-installer-bootstrap. Seems like it does redirect when calling the curl command but I was having issues with it not doing so and this fixed it.

fix: changed packwiz url to reflect new repo address

---

README.md
scripts/start-deployAirplane

This PR updates the Airplane download URL, closing #1295. Also clarifies lack of support for versions >1.17.1. Should be gtg, but please sanity check.

Update Airplane download URL, clarify version support

---

.github/workflows/ci.yml
README.md
scripts/start-setupForgeApiMods
tests/setuponlytests/forgeapimods_file/docker-compose.yml
tests/setuponlytests/forgeapimods_file/forgeapi_mods.json
tests/setuponlytests/forgeapimods_file/require.sh
tests/setuponlytests/forgeapimods_projectids/docker-compose.yml
tests/setuponlytests/forgeapimods_projectids/require.sh
tests/setuponlytests/test.sh

AC: Able to supply information to download a specific version of a mod.
AC: Ability to download any required dependencies listed by the mod.
Concessions:
* Version pinning
**  Forge does not track a mod version, using file name instead.
* Dependency Download
** Forge does not track FileId like it is supposed to, fileId references current mod, not dependency mod. (Code is left in if bug is fixed in forge.)
** Defaulted to just looking up mod and releaseType of Release, this could cause an error if dependency does not support MC version or is not in a Release state.

Adding version pinning and dependency download.

---

.github/workflows/build-multiarch.yml
Dockerfile
docker-versions-create.sh
scripts/start-configuration
scripts/start-deployAirplane
scripts/start-deployBukkitSpigot
scripts/start-deployCanyon
scripts/start-deployCatserver
scripts/start-deployCrucible
scripts/start-deployCustom
scripts/start-deployFTBA
scripts/start-deployForge
scripts/start-deployLimbo
scripts/start-deployMagma
scripts/start-deployMohist
scripts/start-deployPaper
scripts/start-deployPufferfish
scripts/start-deployPurpur
scripts/start-finalExec
scripts/start-utils

Will be able to streamline and improve robustness of build and test of all the Debian variants. That will cover all except the legacy Alpine build of `java8` and the upcoming GraalVM base image, which is RPM based.
cc @shotah

build: switch to matrix builds for Debian based variant builds

---

scripts/start-finalExec

This commit fallback to using the `-Dlog4j2.formatMsgNoLookups=true` flag to allow the container to start even if the download for a patched Log4J2 configuration file fail.
I had the issue this morning with purpurmc.org returning a 503 Service Unavailable.

Use Log4J2 JVM flag when configuration file download fails

---

scripts/start-setupModpack

Only skip up-to-date files with MODS and MODS_FILE

---

scripts/start-setupModpack
scripts/start-utils

This fixes the first problem described in issue #1342. Otherwise the checksum would always be failing on Alpine

Distro aware checksum

---

README.md
scripts/start-deployFabric

The Fabric team have improved the server launch methodology to be more in line with other server types - a launcher specifying the Minecraft, Fabric Launcher, and Fabric Loader versions to use.
https://fabricmc.net/use/server/
This allows for cleaner auto-updates, and fixes #1350 by using the naming convention Fabric use for launcher jar files.
Documentation has been updated to reflect this change, and support for existing configurations is maintained, with the exception of `FABRIC_INSTALLER` and `FABRIC_INSTALLER_URL` (as the installer is no longer
used). These have been replaced by `FABRIC_LAUNCHER` and `FABRIC_LAUNCHER_URL` respectively, to define a custom jar or URL for the launcher as opposed to the installer.

Migrate Fabric server to launcher method

---

README.md

I clarified the use of the JVM_OPTS parameter with an example, since I myself first struggled to figure the correct syntax out. After researching for a bit, I found issue https://github.com/itzg/docker-minecraft-server/issues/943 where an example was provided. I thought it could be helpful for everyone stumbling upon the same problem in the future if an example for correct usage is directly within the documentation.

Added a syntax example for JVM_OPTS

---

.github/workflows/build-multiarch.yml
README.md
build/alpine/install-packages.sh
tests/setuponlytests/test.sh

Added procps to alpine image to resolve autopause compatibility

---

files/sudoers-mc

Fixes failing to start autopause when `GID` is set to `100` (id of existing `users` group)
Fixes #935 and #1233
Alpine branches might need an extra PR afterwards.

use user instead of group in sudoers file

---

build/alpine/install-packages.sh
build/ubuntu/install-packages.sh

The package ttf-dejavu adds 17MB to the alpine images (and probably similar for Ubuntu). I unable to identify through source history why the package was added in the first place. Being a server environment, fonts are not typically applicable.

Removing unused ttf-dejavu package

---

.github/workflows/build-multiarch.yml
.gitignore
scripts/start-setupForgeApiMods
tests/setuponlytests/forgeapimods_projectids/verify.sh

AC: Tests no longer randomly fail for forgeapi projectids
AC: ForgeAPI no longer attempts to redownload downloaded packages. 
Changes:
* Allowed remove old mods to work.
* Using // empty over unset
* Added downloaded modid array to prevent recheck and download of mods.
* Added file check in front of download. (I know '--skip-up-to-date' does this, but messaging is key here I think)
* Added personal build script to gitignore

ForgeAPI: Random failure fix

---

scripts/start-configuration
scripts/start-deployPufferfish
scripts/start-utils
tests/setuponlytests/pufferfish/docker-compose.yml

Major version is used by many third party functions such as Forge API. Would be nice to have a major version split for wide spread use. 
Added new export of MAJOR_VANILLA_VERSION for widespread use.

adding major version for pufferfish

---

README.md
scripts/start-deploySpongeVanilla
tests/setuponlytests/spongevanilla_version_compare/docker-compose.yml
tests/setuponlytests/spongevanilla_version_compare/verify.sh

Fixes #1452
FYI @vorburger , I reverted the README change from #1453 since I realized `VERSION` wasn't the issue.

Fixed version comparisons when using SPONGEVANILLA

---

scripts/start-spiget
tests/setuponlytests/spiget/docker-compose.yml
tests/setuponlytests/spiget/verify.sh

Correct spiget handling of jars that contain jars

---

bin/mc-send-to-console

Fix alpine incompatibility

---

scripts/start-setupModpack

Allow `file://` URIs in `PACKWIZ_URL`.
Fixes #1487.

Fix PACKWIZ_URL not accepting file:// URIs

---

README.md
scripts/start-configuration
scripts/start-deployLoliserver
tests/setuponlytests/loliserver/docker-compose.yml
tests/setuponlytests/loliserver/require.sh
tests/setuponlytests/loliserver/verify.sh

This PR adds support for the more recent hybrid server type LoliServer.
I am not very happy with how releases or updates are handled.
Built jars are just available on a jenkins server which the `lastSuccessfulBuild` gets `curl`ed and used.
In advance iam not sure if all necessary changes are made so i would be thankful for a review/test.

added Loliserver support

---

scripts/start-spiget

Download spiget resources to tempdir under plugins

---

scripts/start-finalExec

This commit ensures expected behaviour when trying out the example below, detailed in the README.
> To let the JVM calculate the heap size from the container declared memory limit, unset MEMORY with an empty value, such as -e MEMORY="". By default, the JVM will use 25% of the container memory limit as the heap limit; however, as an example the following would tell the JVM to use 75% of the container limit of 2GB of memory:
>  `-e MEMORY="" -e JVM_XX_OPTS="-XX:MaxRAMPercentage=75" -m 2000M`

Fix memory env vars being overridden if set to ""

---

scripts/start-deployFTBA

Adding `run.sh` as a server variant allows the code to find the `run.sh` file instead of a server jar. This allows for all script execution to occur, and the finally, `run.sh` itself is used to start the server.
Fixes #1492

Adding 'run.sh' as a variant for FTBA server types

---

README.md

This PR aims to make it easier for users to find documentation on setting a Multiverse/other multi-world plugin's worlds directory path.
I couldn't find a built-in option to set a worlds directory that Multiverse would actually respect and use, so this seems to be the solution. I also added a section on jar file options and pointed it at the aforementioned worlds dir section as an example. 
If this would be more fitting for the [working-with-world-data](https://github.com/itzg/docker-minecraft-server#working-with-world-data) or [working-with-mods-and-plugins](https://github.com/itzg/docker-minecraft-server#working-with-mods-and-plugins) section, I'm happy to update the PR.

Add jarfile options and custom worlds directory path (Multiverse) to docs

---

.github/workflows/build-multiarch.yml

The latest images from eclipse-temurin now default to a 22.04/jammy base image. There is an incompatibility in netty that has been resolved, but is pending on Mojang to update dependencies.
See https://github.com/netty/netty/issues/12343
Example logs with the issue:
```
[00:46:25] [Netty Epoll Server IO #1/WARN]: Unexpected exception in the selector loop.
io.netty.channel.unix.Errors$NativeIoException: epoll_wait(..) failed: Function not implemented
```

Pin base images to focal until netty epoll support is fixed

---

scripts/start-setupServerProperties

1.19 introduced two new server.properties entries, `previews-chat` and `enforce-secured-profile` full details can be found on the full change log at [minecraft.net/en-us/article/the-wild-update-out-today-java](https://www.minecraft.net/en-us/article/the-wild-update-out-today-java)

Add 1.19 server properties

---

README.md
scripts/start-deployPurpur

Add custom download URL for Purpur
Signed-off-by: Bensuperpc <bensuperpc@gmail.com>

Add custom download URL for Purpur

---

scripts/start-deployPufferfish

Added support for Pufferfish 1.19
Compilation & execution have been tested.

Added support for Pufferfish 1.19

---

README.md
scripts/start-finalExec

Pufferfish and its forks can use SIMD operation optimization when a JVM flag is given.

Added support for optimized SIMD operations

---

README.md
examples/docker-compose-magma.yml
scripts/start-deployMagma

Removing channels, since there is no such thing in the API anymore. It will always just get the latest build.
Also using only the installer to more easily be compatible with both 1.16+ and 1.18+ since they both have at least an installer.
Fixes #1579

Update Magma API to V2

---

examples/k8s/vanilla-deployment.yml

During https://github.com/itzg/docker-minecraft-server/discussions/1591 noticed that the k8s example was out of date.

docs: Updated readiness and liveness probes in k8s example

---

scripts/start-deployLimbo

See #994 - Limbo will pass along the world name verbatim, but Minecraft (doesn't appear to) allow uppercase letters in world names.

Default -> default in limbo world name

---

.github/workflows/build-multiarch.yml
Dockerfile
README.md
build/ol/install-gosu.sh
build/ol/install-packages.sh
build/ol/setup-user.sh
scripts/start-utils

Unfortunately, GraalVM EE needs complex setup to build (you need to register to Oracle Container Registry and log in) so only CE for now. Build tested.
RELATED: itzg/docker-minecraft-server#1252

Add GraalVM CE support

---

scripts/start-utils

OL has problem handing zstd, so fixing it with simple workaround.

Fixing zstd uncompression for Oracle Linux

---

build/ol/install-gosu.sh

This one trick makes it build on AArch64 systems, tested on Oracle Cloud A1.Flex instance.

Fix GraalVM images error on AArch64 systems

---

scripts/start-setupModpack

This should hopefully fix the regression introduced in #1608. I tested this with both the java8 and latest image variants.

Alpine build fix #1612

---

examples/docker-compose-magma.yml
scripts/start-deployMagma

Fixes #1589  
Fixes #1598 
Fixes #1600

Download and use Magma server jar rather than installer

---

Dockerfile
README.md
examples/docker-compose-spiget.yml
scripts/start-setupForgeApiMods
scripts/start-setupModpack
scripts/start-spiget
scripts/start-utils

Allow for multiple patterns in REMOVE_OLD_MODS_INCLUDE/EXCLUDE

---

build/ol/install-packages.sh

I haven't tested autopause so this issue went missing. Installing `procps-ng` will fix this issue.

Install procps-ng on Oracle Linux-based images for autopause

---

README.md
scripts/start-setupModpack

Readme should explain what this addition does pretty well and how to use it
Related Issue: #1678

Updates for GH_TOKEN addition for packwiz support

---

files/autostop/stop.sh

In some nonstandard environments (see fly.io for an example) that the
server itself will be PID 1 is not a given. By allowing the user to
choose to use pkill instead they can ensure the autostop feature will
work even in those environments.

Add AUTOSTOP_USE_PKILL option to use pkill instead of kill in autostop feature

---

scripts/start-utils

Even though I couldn't reproduce the issue, looking at the logs in https://github.com/itzg/docker-minecraft-server/discussions/1722#discussioncomment-3602484 it seems logical a bug would result from the combination of strict mode enabled at 
https://github.com/itzg/docker-minecraft-server/blob/a0a046f9f69943978838f8f1d3f1efff7a55d788/scripts/start-configuration#L2
where it would cause start-configuration to bail out.

Change versionLessThan to work in strict mode

---

.github/workflows/verify-pr.yml
Dockerfile
examples/.gitignore
examples/docker-compose-mods-mount.yml
examples/valhelsia2/docker-compose.yml
scripts/start-setupEnvVariables
scripts/start-setupModpack
scripts/start-setupMounts
scripts/start-utils
tests/setuponlytests/conflicting_world_for_spigot_server/verify.sh
tests/setuponlytests/packwiz/docker-compose.yml
tests/setuponlytests/test.sh

Download and use packwiz from Maven repository

---

scripts/start-finalExec
scripts/start-utils

Reported at https://discord.com/channels/660567679458869252/660569755320844308/1018239620955250789

Fixed bug causing isTrue to fail with "parameter not set"

---

scripts/start-setupModpack

- Not providing the side argument causes packwiz to assume we're a client :3
**Introduced here:** https://github.com/itzg/docker-minecraft-server/commit/fabe14db4985a5c8829f85ff9241b6532cf4b972

fix(packwiz): provide side argument to packwiz

---

.github/workflows/build-multiarch.yml

Discovered it was missing via https://github.com/itzg/docker-minecraft-server/discussions/1764

Added ARMv7 build for java8-multiarch

---

.github/release.yml
README.md
scripts/start-setupServerProperties

Avoids confusion experienced by a lot of users where one would think that the container env variables would always be applied. Instead, the default was that they get applied the first time and ignored otherwise.
Resolves #1739

Auto-manage server properties by default

---

scripts/start-configuration
scripts/start-finalExec

Setup MEMORY variables earlier to allow use in Spigot build

---

scripts/start-spiget

if REMOVE_OLD_MODS is True
set installedVersion = 0.0.0

if REMOVE_OLD_MODS = true redownload plugins

---

README.md

This question comes up a lot in Discord 😃

Document command to find host path of anonymous volume

---

README.md
files/auto/pause.sh
files/auto/resume.sh

Implements the suggestion from docker-mc-backup [issue #43](https://github.com/itzg/docker-mc-backup/issues/43#issuecomment-1087984202) to add a `.paused` file when the server is paused so it doesn't get woken up to check the player count. I'll be opening another PR in docker-mc-backup to add a check for the file.
I believe this closes issue #1113 as well.

Add .paused file when server is paused

---

README.md

Addressing concerns discussed at https://discord.com/channels/660567679458869252/660569755320844308/1044195693142749194

Add a lot of clarification to RCON documentation

---

Dockerfile

Bumped mc-image-helper to 1.22.8
Bring in https://github.com/itzg/mc-image-helper/pull/65

Allow for commas in mc-image-helper lists

---

scripts/start-deployCF

Reverts itzg/docker-minecraft-server#1837
Resolves #1849

Revert "Use HTTP accept when downloading CF modpack"

---

README.md

There was a wrong indentation in the description on how to create a multiline MOTD. This way, the displayed was actually `\n` instead of `\\n`.

Fixed format as code for MOTD newline escape

---

README.md
scripts/start-deployBukkitSpigot

Discussed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1057737463092748438)

Added FORCE_REDOWNLOAD support for Bukkit/Spigot

---

Dockerfile

Should solve most of https://github.com/itzg/docker-minecraft-server/issues/1893
...however, dependency handling isn't added yet.

Correct AUTO_CURSEFORGE to only grab server mods

---

Dockerfile
README.md
scripts/start-configuration
scripts/start-deployAutoCF

Correct AUTO_CURSEFORGE to also include library mods

---

Dockerfile
README.md
files/cf-exclude-include.json
scripts/start-deployAutoCF

Use slugs or IDs for include/excludes with AUTO_CURSEFORGE and option for file declaration

---

Dockerfile

Resolves #1916 
Pulls in https://github.com/itzg/mc-image-helper/pull/114

Upgrade image helper to fix Forge 1.7.x downloads

---

files/cf-exclude-include.json

The following mods can be used in conjunction with rubidium, as such they prevent the server from loading

add more rubidium mods

---

.github/workflows/build-multiarch.yml

Resolves #1921 
Applied change mentioned in https://github.com/docker/build-push-action/releases/tag/v3.3.0 since [Watchtower](https://github.com/containrrr/watchtower/discussions/1529) and Azure seem to be non-compliant.

build: disable provenance on image build

---

Dockerfile
README.md
examples/one-block-modded/docker-compose.yml
scripts/start-deployAutoCF

Also:
- Will help with #1927 and similar where the latest files in overrides always need to be written...but keeping world data untouched

For AUTO_CURSEFORGE, auto-set LEVEL from world save provided by modpack

---

README.md
examples/vault-hunters-1-18-2/docker-compose.yml
files/cf-exclude-include.json

Also
- clarified the requirement for non-server file
- added `torohealth-damage-indicators` to excludes
- sorted excludes to make it easier to locate ones when editing
- added example for Vault Hunters 3rd edition

Improve docs for file reference options for AUTO_CURSEFORGE

---

Dockerfile
README.md

Reported [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1068527764606570607)
Pulls in https://github.com/itzg/mc-image-helper/pull/124

Fix handling of CF modpack overrides when files before directories

---

Dockerfile
scripts/start-setupModpack

This reverts commit 3624dc02a34d54c0d7fc33afb8b4b64c78a7ac4c. / https://github.com/itzg/docker-minecraft-server/pull/1987
Discovered that it broke other Modrinth retrievals https://github.com/itzg/mc-image-helper/issues/152

Revert "modrinth: adapt version lookup to API changes (#1987)"

---

Dockerfile
scripts/start-setupModpack

Resolves #1973 the correct way

Ensure Modrinth support specifies paper/purpur loader as needed

---

Dockerfile

Helps #1973 
Pulls in https://github.com/itzg/mc-image-helper/pull/155

Fix Modrinth download when no version files are primary

---

Dockerfile
README.md

Clarify in docs to not port forward RCON unless secure

---

Dockerfile
build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh
files/auto/autopause-daemon.sh
files/auto/knockd-config.cfg
files/sudoers-mc
scripts/start-autopause

Fixes #1969.
There are a couple details that may need to be addressed:
- `seq_cooldown` can't be bigger than `AUTOPAUSE_TIMEOUT_KN` (see last commit). We might want to set a lower bound for both, or expose the cooldown timer as an environment variable.
- I have no idea if the libpcap package has the same name for dnf and alpine, I know that apt has `libpcap0.8` but the other scripts may have to be changed.

Use modified knockd to set a cooldown on port 19132

---

examples/vanilla-tweaks/docker-compose.yml
examples/vanilla-tweaks/vanillatweaks-craftingtweaks.json
examples/vanilla-tweaks/vanillatweaks-datapacks.json
examples/vanilla-tweaks/vanillatweaks-resourcepacks.json

The vanillatweaks example didn´t work, I got the following error:
mc_1  | [mc-image-helper] 12:41:54.892 ERROR : 'vanillatweaks' command failed. Version is 1.25.12
mc_1  | java.lang.NullPointerException: Cannot invoke "me.itzg.helpers.vanillatweaks.model.Type.toString()" because the return value of "me.itzg.helpers.vanillatweaks.model.PackDefinition.getType()" is null
When I checked the tests under tests/setuponlytests/vanillatweaks_file I noticed there were two missing entries in the JSON file.
I corrected this and added the examples for resourcepacks and craftingtweaks as well.
See also https://github.com/itzg/mc-image-helper/issues/163

Correcting and extending vanillatweaks example

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/165

autocf: improve error message when modpack file is missing manifest

---

Dockerfile
build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Fix autopause not working in java8

---

README.md

Resolves https://github.com/itzg/docker-minecraft-server/issues/1276 with documentation.

Adding rootless autopause instructions to the readme.

---

Dockerfile
README.md
examples/atm8/docker-compose.yml
examples/one-block-modded/docker-compose.yml
examples/pixelmon/docker-compose.yml
examples/valhesia5/docker-compose.yml
examples/vault-hunters-1-18-2/docker-compose.yml
tests/setuponlytests/auto_curseforge/docker-compose.yml
tests/setuponlytests/auto_curseforge/require.sh

Resolves #2041 
Pulls in https://github.com/itzg/mc-image-helper/pull/181

autocf: switch to official CurseForge API, but needs CF_API_KEY

---

README.md

Updated the readme for the section about the CF_API_KEY to include info about having to escape the `$` characters in the API Key.

added information on the escaping of $ in the CF API Key

---

README.md

added docs to use env file

---

README.md

Update CF_API_KEY example for docker run

---

README.md
scripts/start-configuration
scripts/start-deployFolia
scripts/start-deployPaper

This PR adds Support for [Folia](https://papermc.io/software/folia).
See #2042

Add Folia support

---

bin/mc-send-to-console

Resolves #2090 
Example from reported issue logged as:
```
[17:24:59] [Server thread/INFO]: [Not Secure] [Server] text1 text2 &acoloredText3
[17:25:18] [Server thread/INFO]: [Not Secure] [Server] text1 text2 > text3
```

Probably quote content passed to mc-send-to-console

---

README.md
scripts/start-deployCanyon

Canyon is on an indefinite hiatus, and a final build has been produced by @KoboDev for the meantime. This changes the default value for `CANYON_BUILD` to "final", and in the instance this is provided, we download this build from their GitHub provided build rather than the CI integration.
The CI server previously provided by Velocity is now 410 Gone, so individual build numbers are not available at present. A future PR may address this by them being made available by another provider, but for now I think this change is enough to keep Canyon servers functional for the meantime.

Download Canyon from GitHub for final build

---

scripts/start-deployCanyon

The team over at Glass have committed to providing updated builds for Canyon after the sunset of Velocity Jenkins.
This PR is a followup to #2108, which restores `lastSuccessfulBuild` as the default, downloading specific releases from the GitHub archive, and offering builds from the Glass CI server where not explicitly handled.

Update Canyon CI link to Glass Launcher

---

Dockerfile
scripts/start-finalExec

Use [CreeperHost/Log4jPatcher](https://github.com/CreeperHost/Log4jPatcher) to patch the Log4Shell vulnerability for server types and versions that are not covered by existing measures. See [#2101](https://github.com/itzg/docker-minecraft-server/issues/2101#issuecomment-1523396342) for some of the affected versions.
The patcher is being applied for all server types between Minecraft version 1.7 - 1.18.0 (inclusive), even though server types VANILLA and PURPUR are already covered by their patched log4j configurations.
Alternatively it could be set up to only cover server types excluding unaffected server types, however in my limited testing the additional patching does not appear to cause any side effects.
As requested a `SKIP_LOG4J_PATCHER` environment variable has been introduced to skip …

Include Log4jPatcher

---

docs/data-directory.md

From [discussion in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1112803737812095026)

docs: clarify bind mounts for Podman also

---

.github/workflows/build-multiarch.yml
.github/workflows/verify-pr.yml
README.md
docs/versions/java.md

Bringing Alpine along for 1.19 and 1.20 MC releases

Moving Java 19 to 20 and adding Alpine

---

docs/mods-and-plugins/index.md

...since it is one of those that doesn't allow automated downloads.
[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1113565094228529255)

docs: don't use EssentialsX as Spiget example

---

docs/configuration/server-properties.md
docs/variables/index.md

I was able to find two files which referenced "minecraft" as the default password. I have changed this to say randomly generated. 
Should fix #2180

Changed rcon password references from "minecraft" to randomly generated

---

docs/mods-and-plugins/index.md
docs/types-and-platforms/mod-platforms/auto-curseforge.md
docs/types-and-platforms/mod-platforms/ftb.md
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
docs/types-and-platforms/server-types/bukkit-spigot.md
docs/types-and-platforms/server-types/fabric.md
docs/types-and-platforms/server-types/forge.md
docs/types-and-platforms/server-types/others.md
docs/types-and-platforms/server-types/paper.md
docs/types-and-platforms/server-types/quilt.md
docs/versions/java.md

Also
- noted error seen when Java 8 is needed

Corrected broken links in types and mods

---

docs/mods-and-plugins/index.md
kustomize/base/kustomization.yml
scripts/start-setupModpack
scripts/start-setupMounts

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1117427932407791686)
Also resolves #2192

For backward compatibility, allow MODS to list plugins for those server types

---

Dockerfile
scripts/start-deployFolia
scripts/start-deployPaper

Resolves #2207 
Pulls in https://github.com/itzg/mc-image-helper/pull/242

Switch to mc-image-helper for installing Paper/Folia

---

.github/workflows/build-multiarch.yml

Provide `stable` image tag that tracks latest repo tag

---

.github/workflows/build-multiarch.yml

Corrected stable tag build configuration

---

README.md
scripts/start-deployMagma

There is a problem with constant updates, which can theoretically break the server startup. I checked the launch of the desired version and it works fine.

added support magma version tags

---

docs/types-and-platforms/server-types/others.md
scripts/start-deployCustom
scripts/start-finalExec

Resolves #943 
And [discussed in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1122147660405686373)

Added CUSTOM_JAR_EXEC

---

docs/misc/autopause-autostop/autopause.md
docs/misc/autopause-autostop/autostop.md
files/auto/autopause-daemon.sh
files/auto/autostop-daemon.sh

I've added a check to the autopause/autostop daemons to see if the `/data/.skip-pause` (`/data/.skip-stop` for autostop) file is present, and if so, prevent autopausing/autostopping.
I've also added notes about this to the docs.

Allow skipping autopause/autostop using a file

---

Dockerfile

Also
- modrinth modpack support when optional env is absent
- Resolves https://github.com/itzg/mc-image-helper/issues/260
- Resolves #2275

Use CXF compatible with Java 8

---

scripts/start-utils

Resolves #2316 
Known downside is that directories that become empty due to the operation will remain. Later, may consider adding a "remove empty directories" option to mc-image-helper.

Corrected REMOVE_OLD_MODS to process file-wise

---

docs/configuration/misc-options.md

Discussed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1138193462731219075)

docs: clarify stop grace period given announce delay

---

tests/setuponlytests/conflicting_world_for_spigot_server/require.sh
tests/setuponlytests/conflicting_world_for_vanilla_server/require.sh
tests/setuponlytests/icon-file-exact/require.sh
tests/setuponlytests/icon-gif-multiframe/require.sh
tests/setuponlytests/icon-png-atscale/require.sh
tests/setuponlytests/spigot_world_for_vanilla_server/require.sh
tests/setuponlytests/spongevanilla_version_compare/require.sh
tests/setuponlytests/vanilla_world_for_spigot_server/require.sh
tests/setuponlytests/vanillatweaks_sharecode/require.sh
tests/setuponlytests/world_from_tar/require.sh
tests/setuponlytests/world_from_tarbz2/require.sh
tests/setuponlytests/world_from_tarzst/require.sh

Some test runs are taking up to 11 minutes on Github Actions. I am adding a `require.sh` to the non-critical ones that check for the variable `EXTENDED_TESTS` to be set.

build: skip some of the setuponly tests by default

---

Dockerfile

Fixes https://github.com/itzg/mc-image-helper/issues/285
Pulls in https://github.com/itzg/mc-image-helper/pull/286

modrinth: resolve "only DEFLATED entries can have EXT"

---

Dockerfile

For #2344 
Pulls in https://github.com/itzg/mc-image-helper/pull/292 which reverts https://github.com/itzg/mc-image-helper/pull/272

modrinth: resolve issue with null versionId in manifest

---

Dockerfile
docs/mods-and-plugins/modrinth.md
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
scripts/start-deployModrinth

Also
- Allow newline delimited (without commas) for MODRINTH_PROJECTS
- Resolves #2344
- Resolves #2351 by trimming whitespace around given whitelist/ops

modrinth: allow installer to ignore missing files

---

.github/dependabot.yml
docs/requirements.txt
mkdocs.yml
scripts/start

It should be the responsibility/choice of the volume creator or orchestration layer, [such as kubernetes fsGroup](https://kubernetes.io/docs/tasks/configure-pod-container/security-context), to alter the group-writability of the `/data` volume.
The existing operation would have needed to further consider the initial user/group of the container rather than just assuming it was root. This was observed [in an issue reported in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1146207314290933902).

Removing chmod g+w at start to tighten security

---

Dockerfile

Resolves #2187
Pulls in https://github.com/itzg/mc-image-helper/pull/309
For example, given `TYPE` of "purpur", it will also resolve plugin versions for Paper and Spigot.

modrinth: support plugin lookups that are compatible with selected loader

---

.github/workflows/build-multiarch.yml
build/ol/install-gosu.sh
build/ol/install-packages.sh
docs/versions/java.md

Oracle GraalVM (formerly GraalVM Enterprise) offers better performance and feature. Since renaming Oracle is allowing free use for production, and redistribution without cost*, so it would be nice to have it as option.
Available versions are:
- `java17-graalvm` with Java 17
- `java20-graalvm` with Java 20
With this PR, this version is getting deprecated:
- `java17-graalvm-ce` with Java 17
Also, I'm planning to upgrade GraalVM images to Oracle Linux 9 in near future. (Possibly after Java 8 is deprecated, since AFAIK Java 8 GraalVM image only has OL 7 and 8 images)
[*]: https://www.oracle.com/java/technologies/javase/jdk-faqs.html#GraalVM-licensing and https://www.oracle.com/downloads/licenses/graal-free-license.html

Add Oracle GraalVM to images

---

Dockerfile
docs/misc/contributing/development.md
docs/mods-and-plugins/modrinth.md
scripts/start-setupModpack

Resolves #2356 
- Introduces `MODRINTH_DOWNLOAD_DEPENDENCIES` variable
- Deprecates `MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES`
- Pulls in https://github.com/itzg/mc-image-helper/pull/310

modrinth: provide dependencies download options

---

docs/variables/index.md

Change the 1G default in the TZ section to be UTC

Fix a typo in the variable portion of the docs

---

README.md
docs/configuration/server-properties.md
docs/types-and-platforms/server-types/others.md
docs/variables/index.md
examples/multi-project/servers/mc-plugins/LuckPerms/config.yml

The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all the URLs to the new domain: minecraft.wiki

Update Minecraft Wiki links to new domain after fork

---

.github/workflows/build-multiarch.yml
docs/versions/java.md

Deprecates java20-graalvm since Java 20 is not LTS.

Added image variant for GraalVM Java 21

---

Dockerfile

For CurseForge modpack files that need manual download, provide the web page to the file itself and not just the mod.
Also, writes out `server.properties` as UTF-8 to retain unicode characters rather than needing to escape them. Part of #2433.

auto-cf: for manual downloads, provide file page

---

docs/misc/deployment/index.md

I work since quite some time on a Kubernetes operator to manage flawlessly a dynamic Minecraft infrastructure (with proxies and servers working together). It uses the docker-minecraft-server and docker-bungeecord images under-the-hood and they are a huge time saver (thanks a lot!).
I found out that there was a new documentation website, so I took my chance to add a backlink to my work on the Deployment section.
I also refined a bit the chapters in this same section to group by deployment target (Kubernetes, AWS), so adding more in the future will be clearer.
Rendered documentation page (courtesy of ReadTheDocs): https://docker-minecraft-server--2454.org.readthedocs.build/en/2454/misc/deployment/#supporting-articles

docs: refine deployment chapters and add section about Shulker

---

Dockerfile

For https://github.com/itzg/easy-add/issues/21

build: upgrade easy-add built with Go 1.20.10

---

files/cf-exclude-include.json

For #2471
From the description it sounds like a client-side only mod:
> Embeddium is an unofficial fork of Sodium based off Rubidium, with additional changes and bugfixes to integrate it with the Forge modding ecosystem.

auto-cf: exclude embeddium by default

---

docs/configuration/server-properties.md
scripts/start-setupServerProperties

Escape unicode in server.properties by default when less than 1.20

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/346
Helps to resolve the following. To increase the timeout, set the env var `FETCH_CONNECTION_POOL_PENDING_ACQUIRE_TIMEOUT` to a larger duration such as "PT240S"
```
reactor.core.Exceptions$ReactiveException: reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
at reactor.core.Exceptions.propagate(Exceptions.java:408)
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
at reactor.core.publisher.Mono.block(Mono.java:1712)
at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpack(CurseForgeInstaller.java:551)
at me.itzg.helpers.curseforge.CurseForgeInstaller.resolveModpackFileAndP …
```

For Auto CurseForge etc, increase default connection pool acquire timeout

---

.github/workflows/discord.yml

Add an on-publish step to send a Discord notification when a release is published.
Additionally:
- removed old workflow names
- format the args a little nicer
- remove the redundant expression syntax on `if:`
I assume this will go to the `#ci` channel in Discord. Felt like `#releases` would make more sense, but I'm assuming that's just official Minecraft releases and integrated via Discord.

Add Discord Release Notification

---

docs/types-and-platforms/server-types/hybrids.md
scripts/start-configuration
scripts/start-deployKetting

Since maintaining of magma project [has been stopped](https://git.magmafoundation.org/magmafoundation/magma-1-20-x/-/commit/4e7abe37403c47d09b74b77bcfc26a19b18f5891), I will add a support Ketting server for MC 1.20.2+ hybrid server.

Support ketting hybrid server

---

docs/types-and-platforms/server-types/hybrids.md
scripts/start-configuration
scripts/start-deployMagmaMaintained

I have implemented a support for [Magma maintained](https://github.com/magmamaintained/) which is an alternative project for terminated Magma project. It supports a bit old versions of Minecraft "1.12.2", "1.18.2", "1.19.3", and "1.20.1".

Add a support for magma maintained

---

Dockerfile
scripts/start-finalExec

This enables the work that was started in the mc-server-runner pull request to add a remote SSH console. 
https://github.com/itzg/mc-server-runner/pull/56
- Updates mc-server-runner to 1.10.0
- Adds `ENABLE_SSH` setting 
Built the docker container locally on an ARM64 system (M1 Mac mini with an Ubuntu VM running docker). Started a (Fabric) server with ENABLE_SSH set and the 2222 port exposed. Was able to login from a standard ssh client and issue commands to it. Docker logs were checked and confirmed that the output was sent to both locations and I could audit SSH connections. 
Discovered that the default password of 'minecraft' is never usable with the container due to the configuration scripts generating a scrambled password when RCON_PASSWORD is not defined.
Checked to ensure that the …

Allow Remote Console to be Enabled

---

Dockerfile

Resolves #2450
Also clarifies confusion caused by "Filename" column is now called "Version Name". The actual filename has also been added (back) as a column.

cf: allow for browser named files in final output

---

Dockerfile
bin/mc-send-to-console
scripts/start-finalExec

Discussed [in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1198277528637423626)
Pulls in https://github.com/itzg/mc-server-runner/pull/57

Directly attach stdin of server process by default

---

files/auto/autopause-fcns.sh

From [discussion in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1198425036734865442)

Handle I/O timout type errors from autopause mc-monitor call

---

build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Apply cap_net_raw to knockd to allow rootless execution

---

Dockerfile
docs/configuration/server-properties.md

Resolves https://github.com/itzg/docker-minecraft-server/issues/2645
Observed with https://www.curseforge.com/minecraft/modpacks/age-of-engineering/files/2503175
Also
- adds and uses by default the PlayerDB API for resolving whitelist and ops. Pulls in https://github.com/itzg/mc-image-helper/pull/393

auto-cf: support modpack zips using IMPLODE compression method

---

Dockerfile
docs/types-and-platforms/mod-platforms/auto-curseforge.md
scripts/start-deployAutoCF

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1205669805684949022)
Modpack https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4724273 was patching gregtech at startup
Pulls in https://github.com/itzg/mc-image-helper/pull/395

auto-cf: add option to ignore files missing from previous installation

---

Dockerfile
docs/commands.md
examples/docker-compose.yml

Pulls in https://github.com/itzg/mc-server-runner/pull/60

Fixed support for mc-send-to-console

---

Dockerfile
docs/types-and-platforms/server-types/hybrids.md
scripts/start-configuration
scripts/start-deployKetting

Fixes #2650
Todo:
Disclaimer: This code is so far untested and requires review/testing.

Use KettingLauncher

---

Dockerfile
scripts/start-setupModpack

Fixed handling of Modrinth mods for NeoForge

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/400
Example of a file that didn't publish correctly https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/3254160

cf: support curseforge files that don't delcare any modloader

---

Dockerfile
tests/setuponlytests/cf_files/listing.txt

https://github.com/itzg/easy-add/pull/30

build: upgrade easy-add to 0.8.4

---

scripts/start-finalExec

Resolves #2690 
but it doesn't make a difference since Forge is not one of the conditions for patching
https://github.com/itzg/docker-minecraft-server/blob/f3bec9406589efd2cd58b79f6cf076159820f196/scripts/start-finalExec#L60-L75
and CreeperHost's log4jpatcher jar was already getting applied.

Use FTB_DIR for log4j2 patched files...hypothetically

---

scripts/start-finalExec

Tested it works. The '' quotes are gone and args are standalone
```
[init] Using Forge supplied run.sh script...
+ exec mc-server-runner --stop-duration 60s --shell bash run.sh --universe /data/worlds
```

fix: Remove EXTAR_ARGS quotes to allow multiple args (fixes #2715)

---

docs/types-and-platforms/server-types/bukkit-spigot.md
scripts/start-deployBukkitSpigot

Caused by #2721 
[Reported in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1219105675595087942)

Successful spigot/bukkit update check caused grep to fail

---

examples/ketting/docker-compose.yml
scripts/start-setupModpack

Hybrid servers using CURSEFORGE_FILES assume mc-mods for Forge

---

examples/docker-compose-tailscale.yml

Added a docker-compose.yml example for creating a minecraft server using tailscale, as suggested in #2744

ADD : Tailscale docker-compose yml example

---

.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/build-multiarch.yml
.github/workflows/stale-check.yml
.github/workflows/verify-pr.yml

Resolves #2756
Also switches github actions runner to ubuntu-22.04

Designate java21 as the latest/default image

---

docs/versions/java.md

Also arranged entries in table to show newest versions first

docs: fixed typo on java versions page

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/416
Resolves https://github.com/itzg/mc-image-helper/issues/415

cf: use fallback download URL when metadata doesn't provide one

---

Dockerfile
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
scripts/start-deployModrinth

modrinth: add option to force include client mods

---

Dockerfile
scripts/start-setupRbac

Follow up to #2797  and pulls in https://github.com/itzg/mc-image-helper/pull/422

paper: fall back to VERSION env var when jar missing metadata

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/423
The custom server jar that prompted these changes did not have a valid structure.

paper: restore requirement of version.json metadata

---

docs/configuration/server-properties.md
examples/multiline-motd/docker-compose.yml

Pointed out in https://github.com/itzg/docker-minecraft-server/discussions/1852#discussioncomment-9449669

docs: add compose example of multiline MOTD

---

Dockerfile
build/alpine/install-packages.sh
build/ol/install-packages.sh
build/ubuntu/install-packages.sh

Removing git-lfs for now due to numerous CVEs including two critical:
```
2C    29H     0M     0L  stdlib 1.18.1
pkg:golang/stdlib@1.18.1
19: sha256:5c0fc48456768933513e10c645395539cfbe17f461f134498e8bfab06907dc4a
/usr/bin/git-lfs (evident by)
x CRITICAL CVE-2023-24540
https://scout.docker.com/v/CVE-2023-24540
Affected range : <1.19.9
Fixed version  : 1.19.9
x CRITICAL CVE-2023-24538
https://scout.docker.com/v/CVE-2023-24538
Affected range : <1.19.8
Fixed version  : 1.19.8
x HIGH CVE-2023-29403
https://scout.docker.com/v/CVE-2023-29403
Affected range : <1.19.10
Fixed version  : 1.19.10
x HIGH CVE-2022-30580
https://scout.docker.com/v/CVE-2022-30580
Affected range : >=1.18.0-0
: <1.18.3
Fixed version  : 1.18.3
x HIGH CVE-2023-45287
https://scout.docker.com/v/CVE-2023-45287
Affected range : …
```

build: upgrading git-lfs from packagecloud

---

.github/workflows/build-multiarch.yml
docs/versions/java.md

Test keeps failing and needs to be investigated later.
```
Starting Tests on multi-part-motd
Network multi-part-motd_default  Creating
Network multi-part-motd_default  Created
Container multi-part-motd-mc-1  Creating
Container multi-part-motd-mc-1  Created
Container multi-part-motd-mc-1  Starting
Container multi-part-motd-mc-1  Started
multi-part-motd Result: failed=true
failed to ping mc:25565 : could not connect to Minecraft server: dial tcp: lookup mc on 127.0.0.11:53: server misbehaving Container multi-part-motd-monitor-run-6ba4dae01354  Stopping
```

build: disable java17-openj9 for now

---

scripts/start-finalExec

The Curseforge server type has not been using the specified memory options. The startup logs (screenshot below) and server memory usage indicate that only 4GB is allocated regardless of the values set in the environment variables. Min 8GB, Max 16GB, and Aikar's flags have been enabled but the java args remain at -Xms4G -Xmx4G.
The issue is that the launch script used by /data/FeedTheBeast/start.sh uses the variables set in /data/FeedTheBeast/variables.txt to determine java launch options. The docker scripts set the desired launch options to variables but never write them to this file.
The proposed change replaces the current JAVA_ARGS variable in variables.txt with the ones defined within the script. Logs from the revised build show the desired result below.

Enhance CurseForge server packs that use variables.txt

---

files/cf-exclude-include.json

i added zume, it was producing a crash on industrial-village modpack, the creator said that it was client only.

Add zume to cf-exclude-include.json

---

Dockerfile

Pulls in
- https://github.com/itzg/easy-add/pull/32
- https://github.com/itzg/restify/pull/34
- https://github.com/itzg/mc-monitor/pull/88
- https://github.com/itzg/rcon-cli/pull/62
- https://github.com/itzg/mc-server-runner/pull/73

build: upgrade tools to Go 1.22.4

---

examples/spiget/docker-compose.yml
scripts/start-spiget
scripts/start-utils

[Reported in Discord](https://discord.com/channels/660567679458869252/660569755320844308/1250536212318523514)
> After I added the SPIGET_RESOURCES line to my docker_compose, I received an variable unboiund error that crashed the container from the variable: REMOVE_OLD_MODS_EXCLUDE:
I did not set this variable since I do not need it I think.

Fixed issue of unbound REMOVE_OLD_MODS_EXCLUDE variable when using SPIGET_RESOURCES

---

files/cf-exclude-include.json

added true-darkness because it is a client only mod. https://www.curseforge.com/minecraft/mc-mods/true-darkness

Add true-darkness to CF global excludes

---

Dockerfile
docs/types-and-platforms/server-types/paper.md
scripts/start-deployPaper

Resolves #2811
Pulls in https://github.com/itzg/mc-image-helper/pull/437

paper: consider release channel when selecting version/build

---

Dockerfile

neoforge: correctly handle versioning that drops the ".0"

---

Dockerfile
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
examples/bmc4/docker-compose.yml
examples/prominence2/docker-compose.yml
files/modrinth-exclude-include.json
scripts/start-deployModrinth

Pulls in https://github.com/itzg/mc-image-helper/pull/442

modrinth: add support for default excludes/includes

---

scripts/start-setupWorld

noticed that the "copy existing world" ability does not check if a level path is absolute, and appends it to /data/, added simple regex ( ^\/.*$ ) check to see if LEVEL is absolute

add check for absolute directories to world copy script

---

docs/mods-and-plugins/modrinth.md

[From Discord](https://discord.com/channels/660567679458869252/660567682751528981/1259204952320905348)

Clarify MODRINTH_ALLOWED_VERSION_TYPE inclusion

---

files/cf-exclude-include.json

A commit was done to exclusions causing an error 'unable to resolve slug into ID (no matches): foamfix-for-minecraft. However, this is no longer the mod name so caused an error https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod.

Changed foamfix mod name

---

files/cf-exclude-include.json

https://github.com/itzg/docker-minecraft-server/issues/2968#issuecomment-2212320299
I confirmed that ATM9 launches normally locally after removing JEI from the exclusion list.

Remove JEI from exclusion list to fix ATM9 launch issue

---

docs/misc/autopause-autostop/autostop.md
scripts/start-finalExec

This fixes #2828, and resolves the concerns in #2838.
Specifically, it adds an env of `USES_PROXY_PROTOCOL`, and when present, passes the `--use-proxy` argument to mc-health

Add use-proxy support to health extra args

---

files/auto/autopause-fcns.sh

I missed this in my previous PR, #2973. This makes it so the autostop monitor is proxy aware as well

Update the autopause server listener to be proxy aware

---

scripts/start-utils

Hi, how are you? I've been using the lib for a few months now, but I notice a slowdown when trying to start, and when analyzing and testing I realized that most of it is because of the versionLessThan function, so I redid it in bash script, did some tests and everything worked fine.

Optimize startup on versionLessThan function

---

files/cf-exclude-include.json

It is not a client mod -- it's a utility library for other mods
https://www.curseforge.com/minecraft/mc-mods/necronomicon
Was incorrectly added in https://github.com/itzg/docker-minecraft-server/pull/2964

auto-cf: remove necronomicon from global exclusions

---

Dockerfile
docs/types-and-platforms/server-types/paper.md

Resolves #2992
Pulls in https://github.com/itzg/mc-image-helper/pull/455

paper: suggest other release channel when build not found

---

scripts/start-deployPaper
scripts/start-finalExec
scripts/start-setupEnvVariables
scripts/start-utils

paper: download default configs before patching

---

bin/rcon-cmds-daemon.sh

Uses `echo -e` to interpret any included backslash escapes within `RCON_CMDS_`. Such as the literal `\n` newlines.
Fixes #3007

Interpret backslash escapes for RCON_CMDS

---

build/alpine/install-packages.sh
build/ol/install-gosu.sh
build/ol/install-packages.sh
build/run.sh
build/ubuntu/install-packages.sh

Updated and Improved install-packages.sh. Added comments, error handling, and enhanced readability of script.

Updated and Improved install scripts.

---

docs/misc/examples.md
examples/lazymc/docker_compose.yml

I have created a docker container which wraps LazyMc add adds the functionality to control a minecraft container
I have updated the docs to add this as an example. Feel free to check out the project here: https://github.com/joesturge/lazymc-docker-proxy

docs: updated with example on how to setup lazymc with minecraft container

---

docs/configuration/server-properties.md
files/property-definitions.json

I think I've done what I need to add this server property.
`hide-online-players` was added in 1.18 21w44a and prevents sending of player list on status requests

Added hide-online-players server property

---

docs/types-and-platforms/server-types/hybrids.md

We removed Github Packages, because they kept failing our publishes and causing pain for us.

Ketting removed GithubPackages

---

docs/types-and-platforms/server-types/paper.md
scripts/start-deployFolia

[Reported in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1269287470646824970)
```
mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Aug  3 13:17 /data'
mc-1  | [init] Resolving type given FOLIA
mc-1  | [mc-image-helper] 13:18:56.782 ERROR : Invalid parameter provided for 'install-paper' command: No build found with channel 'default'. Perhaps try a different channel: experimental
mc-1  | [init] ERROR: failed to download folia
```

Added support for FOLIA_CHANNEL

---

files/cf-exclude-include.json
files/modrinth-exclude-include.json

Here are the URLs just to double check the IDs
https://www.curseforge.com/minecraft/mc-mods/just-zoom
https://modrinth.com/mod/just-zoom
This mod prevents the server from starting since it's dependency Konkrete was added to the global exclude. It seems to be a wrongly declared client side mod.

Add just-zoom (jar: justzoom) to global exclude

---

docs/configuration/server-properties.md
scripts/start-setupRbac

The previous default of "SKIP" was only chosen for backward compatibility. It has become apparent that using that default is misleading for users new to this docker image.

Default EXISTING_OPS_FILE and EXISTING_WHITELIST_FILE to MERGE

---

docs/configuration/server-properties.md
files/property-definitions.json

This new server property was added in [Java Edition 24w33a](https://minecraft.wiki/w/Java_Edition_24w33a). I was a bit unsure whether to open the PR now or wait till 1.21.2 is out, but since the image supports running snapshot versions I thought it would make sense to add it now.

add new server property in 24w33a

---

Dockerfile

Refer to https://docs.docker.com/reference/dockerfile/#healthcheck

Healthcheck interval is now 60s with start interval 5s

---

docs/variables.md

Removed duplicated <code>RCON_CMDS_STARTUP</code>

docs: removed duplicated RCON_CMDS variable

---

Dockerfile

For #3080
Some modpacks how have three-part modloader IDs like neoforge-1.20.1-47.1.99 rather than neoforge-47.1.99
Bring in https://github.com/itzg/mc-image-helper/pull/473

auto-cf: support three-part modloader IDs

---

.github/workflows/build-multiarch.yml
docs/versions/java.md

The Java 8 version used for Alpine is stuck on a really old version and is not compatible with Java operation shown in stack trace:
```
[mc-image-helper] 18:57:31.001 ERROR : 'get' command failed. Version is 1.39.12
java.lang.UnsupportedOperationException: The method shutdownOutput() is not supported in SSLSocket
at sun.security.ssl.BaseSSLSocketImpl.shutdownOutput(BaseSSLSocketImpl.java:228)
at org.apache.hc.core5.http.impl.io.BHttpConnectionBase.close(BHttpConnectionBase.java:252)
at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.close(DefaultBHttpClientConnection.java:71)
at org.apache.hc.client5.http.impl.io.DefaultManagedHttpClientConnection.close(DefaultManagedHttpClientConnection.java:176)
at org.apache.hc.core5.pool.PoolEntry.discardConnection(PoolEntry.java:180)
at …
```

build: deprecating java8-alpine (for now)

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/480
Can be disabled by setting `CF_DISABLE_API_CACHING` to "true"

curseforge: cache get mod info and file API calls to disk

---

bin/mc-send-to-console

I found an error in the conditional statement` if [ "$(id -u)" != 0 ]; then`. 
This condition incorrectly allows the ‘minecraft’ user to access the pipe `/tmp/minecraft-console-in` when the UID is 0 (i.e., when running as the root user), resulting in permission errors. 
This pull request corrects the erroneous check.

Fix mc-send-to-console running with uid=0(root)

---

examples/modrinth/local-modpack/docker-compose.yml

missing port configuration on docker compose for local modrinth modpack setup

port configuration for local modrinth modpack setup

---

docs/mods-and-plugins/index.md
docs/types-and-platforms/index.md
docs/types-and-platforms/mod-platforms/auto-curseforge.md
docs/types-and-platforms/mod-platforms/curseforge.md
docs/types-and-platforms/mod-platforms/ftb.md
docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
examples/aof7/docker-compose.yml
examples/atm8/docker-compose.yml
examples/atm9/docker-compose.yml
examples/auto-cf/modpack-manifest/docker-compose.yml
examples/auto-cf/using-excludes/docker-compose.yml
examples/bettermc/docker-compose.yml
examples/bmc4/docker-compose.yml
examples/modrinth-modpack/docker-compose.yml
examples/modrinth/local-modpack/docker-compose.yml
examples/one-block-modded/docker-compose.yml
examples/pixelmon/docker-compose.yml
examples/prominence2/docker-compose.yml
examples/rad2/compose.yaml
examples/rlcraft/docker-compose.yml
examples/valhesia5/docker-compose.yml
examples/vault-hunters-1-18-2/docker-compose.yml
scripts/start-configuration
scripts/start-deployAutoCF
scripts/start-deployModrinth
scripts/start-setupModpack
tests/setuponlytests/auto_curseforge/docker-compose.yml

#3115 rename MOD_PLATFORM to MODPACK_PLATFORM

---

scripts/start-configuration

Was seeing these warnings even when only `MODPACK_PLATFORM` was set:
```
[init] [WARN] Avoid setting TYPE and MODPACK_PLATFORM 
```
Follow up to #3120. Forgot that TYPE defaults to "VANILLA"

Fix incorrect warning about setting TYPE and MODPACK_PLATFORM

---

scripts/start-deployFTBA

fix start-deployFTBA

---

files/cf-exclude-include.json

https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks  https://www.curseforge.com/minecraft/mc-mods/xaeroplus
I tested both with BetterMC4 and i got crashes due to being client-only

Added xaeroplus and yungs-menu-tweaks to the exclude list

---

scripts/start-deployFTBA

[Reported in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1315710582175039546)
Follow up to #3177
```
mc  | [init] Installing modpack ID 100, version ID 6647
mc  | [init] This could take a while...
mc  | Server installer version 24.622.1046-linux-amd64 commit ea7895792cf8db92694f4feb3c54b6d9866b3d72
mc  | Running installer as user minecraft (1000)
mc  | 2024/12/09 15:57:17 Cannot locate modpack via filename. Error: unable to parse filename: ftb-installer
mc  | 2024/12/09 15:57:17                        _                  _              _
mc  | 2024/12/09 15:57:17                       | |                | |            | |
mc  | 2024/12/09 15:57:17    _ __ ___   ___   __| |_ __   __ _  ___| | _____   ___| |__
mc  | 2024/12/09 15:57:17   | '_ ` _ \ / _ \ / _` …
```

Make sure download new version of FTB installer

---

scripts/start-deployPaper

Thanks a lot for resolving #3211 🙂
I've made some further improvements:
- Only attempt download `paper-global.yml` and `paper-world-defaults.yml` if the version is 1.19 or newer, as [these configuration files were introduced in 1.19](https://forums.papermc.io/threads/paper-1-19.344/).
- Download `paper.yml` if the version is older than 1.19.
- Always download `bukkit.yml`, which is also present in https://github.com/dayyeeet/minecraft-default-configs.

Download `paper.yml` and `bukkit.yml`

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/502

neoforge: grab latest beta even when non-beta release is newer

---

examples/gtnh/docker-compose.yaml

Docker compose errored out due to a missing key, fixed it by adding the key that should go there based on the comment above.

Fixed compose error due to missing key in GTNH example

---

scripts/start-deployMohist

Fixes #3246 
Tested on my end to work
```
% docker run -it -p 25565:25565 -e EULA=TRUE -e TYPE=MOHIST -e VERSION=1.20.1 -e MOHIST_BUILD=922 ana/minecraft-server
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 2 1000 1000 4096 Jan 12 10:31 /data'
[init] Resolving type given MOHIST
[init] Resolved version given 1.20.1 into 1.20.1
[init] Downloading Mohist build 922 for 1.20.1
[init] Creating server properties in /data/server.properties
[init] Disabling whitelist functionality
[mc-image-helper] 10:33:54.686 INFO  : Created/updated 4 properties in /data/server.properties
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
File init exception!
███╗   ███╗  ██████╗  ██╗  ██╗ ██╗ ███████╗ ████████╗
████╗ ████║ ██╔═══██╗ ██║  ██║ ██║ ██╔════╝ …
```

update mohist download script to use new API endpoint

---

examples/gtnh/docker-compose.yaml

[Discussed in Discord](https://discord.com/channels/660567679458869252/660569641550217327/1329256890307186690) where it was confusing that the log said
```
mc-1    | [init] Setting initial memory to 1G and max to 1G
```
but actual use was 6G.

examples: adjust gtnh example to use MEMORY and JVM_OPTS

---

examples/gtnh/docker-compose.yaml

GTNH released version 2.7.2 this just bumps the version

Version bump GTNH to 2.7.2

---

scripts/start-setupDatapack

This PR allows users to add datapacks, that are not zipped, using `DATAPACKS=/path/to/datapack`.

datapack: allow copying from directory

---

Dockerfile

Bump mc-monitor binary to mitigate vulnerability addressed in https://github.com/itzg/mc-monitor/pull/101.

Bump mc-monitor to fix cve

---

Dockerfile
docs/configuration/misc-options.md

Feature introduced by https://github.com/itzg/mc-server-runner/pull/95
Should probably only be merged once a new version of `mc-server-runner` has been released and bumped.
Released in https://github.com/itzg/mc-server-runner/releases/tag/1.12.4

feat: bump mc-server-runner & add note about bypassing `STOP_SERVER_ANNOUNCE_DELAY`

---

docs/mods-and-plugins/index.md
scripts/start-setupModpack

Adding the ability to disable mods for generic packs in `start-setupModpack` through a `DISABLE_MODS` environment variable.
Example of usage for something like running GTNH 2.7.2 with CrucibleMC, where `lwjgl3ify` and `archaicfix` need to be disabled for the pack to work:
```
gtnh:
image: itzg/minecraft-server
container_name: gtnh
tty: true
stdin_open: true
restart: unless-stopped
environment:
TYPE: CRUCIBLE
VERSION: 1.7.10
CRUCIBLE_RELEASE: staging-8ae5051
GENERIC_PACKS: GT_New_Horizons_2.7.2_Server_Java_17-21
GENERIC_PACKS_SUFFIX: .zip
GENERIC_PACKS_PREFIX: https://downloads.gtnewhorizons.com/ServerPacks/
DISABLE_MODS: |
lwjgl3ify-2.1.5.jar
archaicfix-0.7.4.jar
ENABLE_QUERY: true
EULA: TRUE
MEMORY: 8G
JVM_OPTS: -Dfml.readTimeout=180 @crucible-gtnh-java9args.txt
ports:
- '25565:25565' …
```

Feat: Disabling Mods in Generic Packs

---

docs/misc/world-data.md

I am not familiar with ReadTheDocs. If I messed up any formatting, I apologize. I learned that Vanilla Tweaks changed their category names recently. I updated the examples to match those new category names, as well as provided a link to their definition file.

Clarify Vanilla Tweaks file documentation

---

Dockerfile
docs/types-and-platforms/server-types/forge.md
examples/cleanroom/compose.yml
scripts/start-deployForge

For #3274
Pulls in https://github.com/itzg/mc-image-helper/pull/516
Also
- add back support for FORGE_INSTALLER_URL

Add support for Cleanroom (Forge fork) installer

---

scripts/start-setupRbac

The `--append-only` flag was removed from `mc-image-helper manage-users` in commit [5fbfd0e](https://github.com/itzg/mc-image-helper/commit/5fbfd0e31b50f8eab9b115f9681e7a5bd5807b09#diff-ebfa578788a4287084a9d0b5b0c25783b3dea399fd06bbaa9d1f9af88119019cL62). If `APPEND_WHITELIST` or `OVERRIDE_WHITELIST` are set to false the container fails to start. As far as I can tell it is safe to simply remove the section since if neither variable is set to true the script defaults to `--existing=MERGE` which is the desired behavior.

Remove deprecated flag from mc-image-helper command in start-setupRbac

---

files/cf-exclude-include.json

While installing [Dungeons, Dragons and Space Shuttles](https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles) (Minecraft 1.12.2, Forge) with server type `AUTO_CURSEFORGE` the server crashed on start because an old mod named [Sound Reloader](https://www.curseforge.com/minecraft/mc-mods/sound-reloader) is client-side only but was installed server-side.
Given this mod hasn't been updated for over 7 years now, I figure it's easier to exclude it here than to fix the mod itself.
[crash-2025-02-16_16.51.20-server.txt](https://github.com/user-attachments/files/18815488/crash-2025-02-16_16.51.20-server.txt)

Add sound-reload to cf-exclude-include.json

---

Dockerfile
examples/fabric/compose.yml

Resolves #3331
NOTE: only applicable when VERSION, FABRIC_INSTALLER_VERSION, and FABRIC_LOADER_VERSION are set to specific versions

fabric: skip web API access when all versions match installed

---

files/auto/autopause-fcns.sh

Tested locally on versions 1.6 and 1.4. No success on <1.4, but that may be a Java version issue

1863: use SLP for pre-1.7 servers.

---

files/cf-exclude-include.json

This mod confusingly named [Sound​s](https://www.curseforge.com/minecraft/mc-mods/sound) with the slug `sound` is just incorrectly marked and crashes the server on load.

add sound to excluded mods as it crashes server on load.

---

files/cf-exclude-include.json
files/modrinth-exclude-include.json

Excludes this mod https://www.curseforge.com/minecraft/mc-mods/compass-coords (and https://modrinth.com/mod/compass-coords on MR)
Per the mod description "Needed on Client-side only, can't be installed on the server." and sure enough it crashed the server when installed. Came across this while trying to set up a the DawnCraft modpack

Exclude compass-coords globally from cf and mr, client side mod

---

docs/misc/examples.md
examples/lazymc/docker_compose.yml

As per the deprecation warning here: https://github.com/joesturge/lazymc-docker-proxy?tab=readme-ov-file#deprecated
This method is about to be removed from lazymc-docker-proxy

Lazymc - Update misc examples with non-deprecated method of managing lazymc

---

docs/configuration/jvm-options.md

resources key was missing in example:
https://docs.docker.com/reference/compose-file/deploy/#resources
```yaml
deploy:
resources:
limits:
cpus: '0.50'
memory: 50M
pids: 1
reservations:
cpus: '0.25'
memory: 20M`
```

add resources key to docker compose jvm options

---

Dockerfile

Pulls in https://github.com/itzg/mc-image-helper/pull/545
Hoping it reduces cases of
```
Caused by: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response
```

fabric: accept shared-fetch/netty arguments

---

Dockerfile
tests/setuponlytests/auto_curseforge/docker-compose.yml
tests/setuponlytests/test.sh

It was likely causing some newly observed networking issues. I'll need to research further a better way to limit the concurrent file downloads.
See https://github.com/itzg/mc-image-helper/releases/tag/1.41.9
https://github.com/itzg/mc-image-helper/pull/554

Revert (for now) the feature to limit concurrent modpack file downloads

---

files/cf-exclude-include.json

Related to https://github.com/itzg/docker-minecraft-server/issues/3436

Ignoring `particular`

---

files/cf-exclude-include.json

I updated my [All The Mods 10](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10) pack to version [2.46](https://github.com/AllTheMods/ATM-10/blob/main/changelogs/CHANGELOG-ATM10-2.45-2.46.md), and had a crash happen because of [smithing-template-viewer](https://www.curseforge.com/minecraft/mc-mods/smithing-template-viewer).
Therefore I added this mod to the environmental variable to exclude it (after deleting the jar file), and now the server starts just fine.
Thought it best to just have it globally excluded.
EDIT: They just updated to 2.47 ([no github changelog as of this edit](https://github.com/AllTheMods/ATM-10/blob/main/CHANGELOG.md))
Hotfix:
- Updated Smithing Template Viewer to fix a crash when rejoining worlds
- Updated Minecolonies to fix a connection crash
- …

Add smithing-template-viewer to cf-exclude-include.json

---

files/auto/autopause-daemon.sh
files/sudoers-mc
scripts/start

If you are hosting this image for unknown users, sudo access to knockd can be used for privilege escalation _within_ the container.
There needs to be a lot of surrounding functionality for this to be a security risk, and for self-hosted minecraft servers this isn't a concern. I'm not 100% certain this is the correct approach, but I'm happy to make changes as necessary.
If you think this _is_ the correct approach I'm happy to update (with the help of [Peri123214](https://github.com/Peri123214)) the docs outlining the risk once this has been patched.
Big thanks to [Peri123214](https://github.com/Peri123214) for finding this.

patch: conditionally add knockd to sudoers file

---

docs/types-and-platforms/server-types/paper.md
scripts/start-configuration
scripts/start-deployLeaf

preliminary Leaf support. Not yet tested or vetted.

Start work on Leaf support

---

Dockerfile
docs/versions/java.md

Pulls in https://github.com/itzg/mc-image-helper/pull/562
Also includes docs update missing from https://github.com/itzg/docker-minecraft-server/pull/3468 for #3465

Upgrade mc-image-helper to tweak file download logic

---

.github/workflows/build-multiarch.yml
.github/workflows/verify-pr.yml

Preparing for upgrading mc image helper to be built for Java 11 in order to gain language and JDK features.

build: pin mc-image-helper version for Java 8

---

.github/workflows/build-multiarch.yml
docs/versions/java.md

PaperMC calls out Java 16 specifically
https://docs.papermc.io/paper/getting-started/#requirements
Also deprecating java8-jdk, java8-openj9, java8-graalvm-ce since the total number of build variants can't grow unbounded.

Add back java16 variant for Paper 1.16.5 Also - remove non-JRE java8 variants to offset extra builds

---

docs/configuration/server-properties.md

The docs referred to `QUERY_PORT` as the right env var for enabling query in the server properties, but as noted later in the docs that's for configuring the port for query (maps to the `query.port` server property), not for enabling/disabling query.
The correct env var to reference here is `ENABLE_QUERY`, I think. Ref https://github.com/itzg/docker-minecraft-server/blob/master/files/property-definitions.json#L12

Docs: fix env var for enabling query

---

scripts/start-configuration

#3601 modified a call to the uname command. Now when `$DEBUG_MEMORY=true` it throws an error
```
[init] 2025-08-27 15:05:48+02:00 Memory usage and availability (in MB)
+ uname -parts
uname: invalid option -- 't'
Try 'uname --help' for more information.
```
I assume the `-t` switch is a typo since it's not available in any `uname` implementation I'm aware of. I removed it.

Fix typo in uname command in start-configuration

---

files/cf-exclude-include.json

Fixes issue https://github.com/adam9899/MC-Eternal-2/issues/288 that prevented [Eternal 2](https://www.curseforge.com/minecraft/modpacks/mc-eternal-2) from completing world-gen by including [mob-player-animator](https://www.curseforge.com/minecraft/mc-mods/mob-player-animator) in the "forceIncludes" section of cf-exclude-include.json. Also includes [particular-reforged](https://www.curseforge.com/minecraft/mc-mods/particular-reforged) as the eternal-2 client expects this to be on the server.

Fix for Eternal 2 Modpack

---

scripts/start-finalExec

fixes aikar flags always being enabled along-side meowice flags.. I think..
from [conversation in discord server](https://canary.discord.com/channels/660567679458869252/660567682751528981/1413234096989274203)

move USE_AIKAR_FLAGS=TRUE into else block

---

files/shims/rcon-cmds-daemon.sh
scripts/auto/autostop-daemon.sh

Closes https://github.com/itzg/docker-minecraft-server/issues/3665
Found 2 other spots that I assume need to be updated.
There also may be a better way to update this path, not sure what you have in mind.

fix: update autopause-fcns.sh path

---

examples/gtnh/docker-compose.yaml

Bumped pack version to 2.8 (latest stable version) and added several `server.properties` changes so that it better reflects the inteded player experience.

Update Greg Tech New Horizons compose file example
